export type PdfTextExtractionStage =
  | 'text_extracted'
  | 'parser_failed'
  | 'extract_failed'
  | 'dependency_failed'
  | 'runtime_bootstrap_failed';

export type PdfTextExtractionResult = {
  text: string | null;
  extractor: 'pdf_parse';
  warnings: string[];
  stage: PdfTextExtractionStage;
  runtimeBootstrap?: {
    injectedGlobals: Array<'DOMMatrix' | 'ImageData' | 'Path2D'>;
  };
};

type PdfParseInstance = {
  getText(): Promise<{ text?: string | null }>;
  destroy(): Promise<void> | void;
};

type PdfParseConstructor = new (params: { data: Buffer }) => PdfParseInstance;

type PdfParseModule = {
  PDFParse: PdfParseConstructor;
};

type PdfParseLoader = () => Promise<PdfParseModule>;

type CanvasRuntimeModule = Partial<Record<'DOMMatrix' | 'ImageData' | 'Path2D', unknown>>;

type CanvasRuntimeLoader = () => Promise<CanvasRuntimeModule>;

function normalizePdfText(text: string): string {
  const normalized = text
    .replace(/\r\n/g, '\n')
    .replace(/[ \t]+/g, ' ')
    .replace(/\n{3,}/g, '\n\n')
    .trim();

  return normalized
    .replace(/\bnet\s+sal\s+es\b/gi, 'net sales')
    .replace(/\boperat\s+i\s+ng\b/gi, 'operating')
    .replace(/\bcur\s+rent\b/gi, 'current')
    .replace(/\bsharehol\s+ders\b/gi, 'shareholders')
    .replace(/\bequi\s+t\s+y\b/gi, 'equity')
    .replace(/\bli\s+abi\s+l\s+i\s+t\s+i\s+es\b/gi, 'liabilities')
    .replace(/\bTer\s+m\s+debt\b/gi, 'Term debt')
    .replace(/\s+(CONDENSED CONSOLIDATED STATEMENTS? OF )/gi, '\n$1')
    .replace(/\s+(CONDENSED CONSOLIDATED BALANCE SHEETS?)/gi, '\n$1')
    .replace(/\s+(Three Months Ended|Year Ended|ASSETS:|LIABILITIES AND SHAREHOLDERS’ EQUITY:|Current assets:|Non-current assets:|Current liabilities:|Non-current liabilities:|Operating activities:|Investing activities:|Financing activities:)/g, '\n$1')
    .replace(/\s+(Net sales:|Products|Services|Total net sales|Cost of sales:|Total cost of sales|Gross margin|Operating expenses:|Research and development|Selling, general and administrative|Total operating expenses|Operating income|Income before provision for income taxes|Provision for income taxes|Net income|Basic|Diluted|Shares used in computing earnings per share:|Cash and cash equivalents|Commercial paper|Term debt|Cash generated by operating activities|Payments for acquisition of property, plant and equipment|Depreciation and amortization)/g, '\n$1')
    .replace(/\n{3,}/g, '\n\n')
    .trim();
}

async function loadPdfParse(): Promise<PdfParseModule> {
  const mod = await import('pdf-parse');
  const PDFParse = mod?.PDFParse;
  if (typeof PDFParse !== 'function') {
    throw new Error('pdf-parse did not expose the PDFParse class');
  }
  return { PDFParse };
}

async function loadCanvasRuntime(): Promise<CanvasRuntimeModule> {
  const mod = await import('@napi-rs/canvas');
  return {
    DOMMatrix: mod?.DOMMatrix,
    ImageData: mod?.ImageData,
    Path2D: mod?.Path2D,
  };
}

export async function ensurePdfRuntimeGlobals(
  options?: { loadCanvasRuntime?: CanvasRuntimeLoader },
): Promise<Array<'DOMMatrix' | 'ImageData' | 'Path2D'>> {
  const missingGlobals: Array<'DOMMatrix' | 'ImageData' | 'Path2D'> = [];
  if (typeof globalThis.DOMMatrix === 'undefined') missingGlobals.push('DOMMatrix');
  if (typeof globalThis.ImageData === 'undefined') missingGlobals.push('ImageData');
  if (typeof globalThis.Path2D === 'undefined') missingGlobals.push('Path2D');
  if (missingGlobals.length === 0) return [];

  const runtime = await (options?.loadCanvasRuntime ?? loadCanvasRuntime)();
  for (const globalName of missingGlobals) {
    const runtimeValue = runtime[globalName];
    if (typeof runtimeValue === 'undefined') {
      throw new Error(`Canvas runtime did not expose ${globalName}`);
    }
    (globalThis as Record<string, unknown>)[globalName] = runtimeValue;
  }
  return missingGlobals;
}

export async function extractPdfTextServer(
  pdfBuffer: Buffer,
  options?: { loadPdfParse?: PdfParseLoader; loadCanvasRuntime?: CanvasRuntimeLoader },
): Promise<PdfTextExtractionResult> {
  const loader = options?.loadPdfParse ?? loadPdfParse;
  let parser: PdfParseInstance | null = null;
  let injectedGlobals: Array<'DOMMatrix' | 'ImageData' | 'Path2D'> = [];
  try {
    injectedGlobals = await ensurePdfRuntimeGlobals({
      loadCanvasRuntime: options?.loadCanvasRuntime,
    });
    const { PDFParse } = await loader();
    parser = new PDFParse({ data: pdfBuffer });
    const parsed = await parser.getText();
    const text = normalizePdfText(parsed.text ?? '');
    if (!text) {
      return {
        text: null,
        extractor: 'pdf_parse',
        warnings: ['PDF text extraction returned no readable text.'],
        stage: 'parser_failed',
        runtimeBootstrap: { injectedGlobals },
      };
    }
    return {
      text,
      extractor: 'pdf_parse',
      warnings: [],
      stage: 'text_extracted',
      runtimeBootstrap: { injectedGlobals },
    };
  } catch (error) {
    const message = error instanceof Error ? error.message : 'Unknown PDF extraction error';
    const runtimeBootstrapFailed =
      /Canvas runtime did not expose|DOMMatrix is not defined|ImageData is not defined|Path2D is not defined/i.test(message);
    const dependencyFailed =
      /did not expose the PDFParse class|Cannot find package|Cannot find module|ERR_MODULE_NOT_FOUND|ERR_PACKAGE_PATH_NOT_EXPORTED/i.test(
        message,
      );
    return {
      text: null,
      extractor: 'pdf_parse',
      warnings: [`PDF text extraction failed: ${message}`],
      stage: runtimeBootstrapFailed ? 'runtime_bootstrap_failed' : dependencyFailed ? 'dependency_failed' : 'extract_failed',
      runtimeBootstrap: { injectedGlobals },
    };
  } finally {
    if (parser) {
      try {
        await parser.destroy();
      } catch {
        // Ignore parser cleanup errors in the request path.
      }
    }
  }
}
