export type PdfTextExtractionStage = 'text_extracted' | 'parser_failed' | 'extract_failed' | 'dependency_failed';

export type PdfTextExtractionResult = {
  text: string | null;
  extractor: 'pdf_parse';
  warnings: string[];
  stage: PdfTextExtractionStage;
};

type PdfParseInstance = {
  getText(): Promise<{ text?: string | null }>;
  destroy(): Promise<void> | void;
};

type PdfParseConstructor = new (params: { data: Buffer }) => PdfParseInstance;

type PdfParseModule = {
  PDFParse: PdfParseConstructor;
};

type PdfParseLoader = () => Promise<PdfParseModule>;

function normalizePdfText(text: string): string {
  const normalized = text
    .replace(/\r\n/g, '\n')
    .replace(/[ \t]+/g, ' ')
    .replace(/\n{3,}/g, '\n\n')
    .trim();

  return normalized
    .replace(/\bnet\s+sal\s+es\b/gi, 'net sales')
    .replace(/\boperat\s+i\s+ng\b/gi, 'operating')
    .replace(/\bcur\s+rent\b/gi, 'current')
    .replace(/\bsharehol\s+ders\b/gi, 'shareholders')
    .replace(/\bequi\s+t\s+y\b/gi, 'equity')
    .replace(/\bli\s+abi\s+l\s+i\s+t\s+i\s+es\b/gi, 'liabilities')
    .replace(/\bTer\s+m\s+debt\b/gi, 'Term debt')
    .replace(/\s+(CONDENSED CONSOLIDATED STATEMENTS? OF )/gi, '\n$1')
    .replace(/\s+(CONDENSED CONSOLIDATED BALANCE SHEETS?)/gi, '\n$1')
    .replace(/\s+(Three Months Ended|Year Ended|ASSETS:|LIABILITIES AND SHAREHOLDERS’ EQUITY:|Current assets:|Non-current assets:|Current liabilities:|Non-current liabilities:|Operating activities:|Investing activities:|Financing activities:)/g, '\n$1')
    .replace(/\s+(Net sales:|Products|Services|Total net sales|Cost of sales:|Total cost of sales|Gross margin|Operating expenses:|Research and development|Selling, general and administrative|Total operating expenses|Operating income|Income before provision for income taxes|Provision for income taxes|Net income|Basic|Diluted|Shares used in computing earnings per share:|Cash and cash equivalents|Commercial paper|Term debt|Cash generated by operating activities|Payments for acquisition of property, plant and equipment|Depreciation and amortization)/g, '\n$1')
    .replace(/\n{3,}/g, '\n\n')
    .trim();
}

async function loadPdfParse(): Promise<PdfParseModule> {
  const mod = await import('pdf-parse');
  const PDFParse = mod?.PDFParse;
  if (typeof PDFParse !== 'function') {
    throw new Error('pdf-parse did not expose the PDFParse class');
  }
  return { PDFParse };
}

export async function extractPdfTextServer(
  pdfBuffer: Buffer,
  options?: { loadPdfParse?: PdfParseLoader },
): Promise<PdfTextExtractionResult> {
  const loader = options?.loadPdfParse ?? loadPdfParse;
  let parser: PdfParseInstance | null = null;
  try {
    const { PDFParse } = await loader();
    parser = new PDFParse({ data: pdfBuffer });
    const parsed = await parser.getText();
    const text = normalizePdfText(parsed.text ?? '');
    if (!text) {
      return {
        text: null,
        extractor: 'pdf_parse',
        warnings: ['PDF text extraction returned no readable text.'],
        stage: 'parser_failed',
      };
    }
    return {
      text,
      extractor: 'pdf_parse',
      warnings: [],
      stage: 'text_extracted',
    };
  } catch (error) {
    const message = error instanceof Error ? error.message : 'Unknown PDF extraction error';
    const dependencyFailed =
      /did not expose the PDFParse class|Cannot find package|Cannot find module|ERR_MODULE_NOT_FOUND|ERR_PACKAGE_PATH_NOT_EXPORTED/i.test(
        message,
      );
    return {
      text: null,
      extractor: 'pdf_parse',
      warnings: [`PDF text extraction failed: ${message}`],
      stage: dependencyFailed ? 'dependency_failed' : 'extract_failed',
    };
  } finally {
    if (parser) {
      try {
        await parser.destroy();
      } catch {
        // Ignore parser cleanup errors in the request path.
      }
    }
  }
}
