import { PDFParse } from 'pdf-parse';

export type PdfTextExtractionStage = 'text_extracted' | 'parser_failed' | 'extract_failed';

export type PdfTextExtractionResult = {
  text: string | null;
  extractor: 'pdf_parse';
  warnings: string[];
  stage: PdfTextExtractionStage;
};

function normalizePdfText(text: string): string {
  const normalized = text
    .replace(/\r\n/g, '\n')
    .replace(/[ \t]+/g, ' ')
    .replace(/\n{3,}/g, '\n\n')
    .trim();

  return normalized
    .replace(/\bnet\s+sal\s+es\b/gi, 'net sales')
    .replace(/\boperat\s+i\s+ng\b/gi, 'operating')
    .replace(/\bcur\s+rent\b/gi, 'current')
    .replace(/\bsharehol\s+ders\b/gi, 'shareholders')
    .replace(/\bequi\s+t\s+y\b/gi, 'equity')
    .replace(/\bli\s+abi\s+l\s+i\s+t\s+i\s+es\b/gi, 'liabilities')
    .replace(/\bTer\s+m\s+debt\b/gi, 'Term debt')
    .replace(/\s+(CONDENSED CONSOLIDATED STATEMENTS? OF )/gi, '\n$1')
    .replace(/\s+(CONDENSED CONSOLIDATED BALANCE SHEETS?)/gi, '\n$1')
    .replace(/\s+(Three Months Ended|Year Ended|ASSETS:|LIABILITIES AND SHAREHOLDERS’ EQUITY:|Current assets:|Non-current assets:|Current liabilities:|Non-current liabilities:|Operating activities:|Investing activities:|Financing activities:)/g, '\n$1')
    .replace(/\s+(Net sales:|Products|Services|Total net sales|Cost of sales:|Total cost of sales|Gross margin|Operating expenses:|Research and development|Selling, general and administrative|Total operating expenses|Operating income|Income before provision for income taxes|Provision for income taxes|Net income|Basic|Diluted|Shares used in computing earnings per share:|Cash and cash equivalents|Commercial paper|Term debt|Cash generated by operating activities|Payments for acquisition of property, plant and equipment|Depreciation and amortization)/g, '\n$1')
    .replace(/\n{3,}/g, '\n\n')
    .trim();
}

export async function extractPdfTextServer(pdfBuffer: Buffer): Promise<PdfTextExtractionResult> {
  let parser: PDFParse | null = null;
  try {
    parser = new PDFParse({ data: pdfBuffer });
    const parsed = await parser.getText();
    const text = normalizePdfText(parsed.text ?? '');
    if (!text) {
      return {
        text: null,
        extractor: 'pdf_parse',
        warnings: ['PDF text extraction returned no readable text.'],
        stage: 'parser_failed',
      };
    }
    return {
      text,
      extractor: 'pdf_parse',
      warnings: [],
      stage: 'text_extracted',
    };
  } catch (error) {
    const message = error instanceof Error ? error.message : 'Unknown PDF extraction error';
    return {
      text: null,
      extractor: 'pdf_parse',
      warnings: [`PDF text extraction failed: ${message}`],
      stage: 'extract_failed',
    };
  } finally {
    if (parser) {
      try {
        await parser.destroy();
      } catch {
        // Ignore parser cleanup errors in the request path.
      }
    }
  }
}
