services:
  - type: web
    name: finmodai-professional
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: PORT
        value: 8000
      - key: ALPHAVANTAGE_API_KEY
        value: PFP7ETK9CEHSFEH
      - key: FMP_API_KEY
        value: 6FxULbNNuO1VAt6pkbr7MgzCaMlAIZjK
      - key: FRED_API_KEY
        value: demo