services:
  - type: web
    name: finmodai-professional
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: PORT
        value: 8000
      - key: ALPHAVANTAGE_API_KEY
        value: EQJS9ZZ669MZCWPC
      - key: FMP_API_KEY
        value: 6FxULbNNuO1VAt6pkbr7MgzCaMlAIZjK 
      - key: FRED_API_KEY
        value: 4987b43f319ba1c5d862ddabbbc4ecf8
      - key: GOOGLE_FINANCE_EMAIL
        value: aromain27@amherst.edu
      - key: GOOGLE_FINANCE_TOKEN
        value: 3bafe26dc9d0e1f9