"""
Configuration for FinModAI Backend
Environment-based settings with sensible defaults
"""

from typing import Optional
from pydantic_settings import BaseSettings
from pydantic import Field


class Settings(BaseSettings):
    """Application settings with environment variable support"""

    # Application
    APP_NAME: str = "FinModAI"
    APP_VERSION: str = "1.0.0"
    DEBUG: bool = Field(default=False, env="DEBUG")

    # Data Configuration
    DATA_MODE: str = Field(default="production", env="DATA_MODE")
    DATA_STALENESS_MAX_MIN: Optional[int] = Field(default=None, env="DATA_STALENESS_MAX_MIN")
    REQUIRE_MIN_FUND_YEARS: int = Field(default=3, env="REQUIRE_MIN_FUND_YEARS")

    # JWT Authentication
    JWT_SECRET: str = Field(..., env="JWT_SECRET")
    JWT_ALGORITHM: str = Field(default="HS256", env="JWT_ALGORITHM")
    JWT_EXPIRATION_HOURS: int = Field(default=24, env="JWT_EXPIRATION_HOURS")

    # Database
    DATABASE_URL: str = Field(default="sqlite:///./finmodai.db", env="DATABASE_URL")

    # Export
    EXPORT_FOOTER_NOTE: str = Field(
        default="Generated by FinModAI • For discussion only • See provenance.",
        env="EXPORT_FOOTER_NOTE",
    )

    # API Keys (optional for MVP)
    ALPHAVANTAGE_API_KEY: Optional[str] = Field(
        default=None, env="ALPHAVANTAGE_API_KEY"
    )
    FINNHUB_API_KEY: Optional[str] = Field(default=None, env="FINNHUB_API_KEY")
    POLYGON_API_KEY: Optional[str] = Field(default=None, env="POLYGON_API_KEY")
    ANTHROPIC_API_KEY: Optional[str] = Field(default=None, env="ANTHROPIC_API_KEY")

    # CORS
    CORS_ORIGINS: list[str] = Field(
        default=["http://localhost:3000", "http://localhost:5000"], env="CORS_ORIGINS"
    )

    # File Storage
    UPLOAD_FOLDER: str = Field(default="./uploads", env="UPLOAD_FOLDER")
    MAX_UPLOAD_SIZE: int = Field(
        default=16 * 1024 * 1024, env="MAX_UPLOAD_SIZE"
    )  # 16MB

    # API Limits
    DEFAULT_SNAPSHOT_LIMIT: int = Field(default=100, env="DEFAULT_SNAPSHOT_LIMIT")
    MAX_SNAPSHOT_LIMIT: int = Field(default=1000, env="MAX_SNAPSHOT_LIMIT")
    DEFAULT_LEADERS_LIMIT: int = Field(default=3, env="DEFAULT_LEADERS_LIMIT")
    MAX_LEADERS_LIMIT: int = Field(default=50, env="MAX_LEADERS_LIMIT")

    class Config:
        env_file = ".env"
        case_sensitive = True


# Global settings instance
settings = Settings()


def validate_settings() -> None:
    """Validate critical settings at startup"""
    if settings.DATA_MODE == "production":
        # Ensure JWT secret is set in production
        if not settings.JWT_SECRET or len(settings.JWT_SECRET) < 32:
            raise ValueError(
                "JWT_SECRET must be at least 32 characters in production mode"
            )

        # Ensure DATA_STALENESS_MAX_MIN is explicitly set in production
        if settings.DATA_STALENESS_MAX_MIN is None:
            raise RuntimeError(
                "Required env var DATA_STALENESS_MAX_MIN is not set for production."
            )

        print("✅ Production mode: Dummy data blocked")
    else:
        # In dev/test, default to 30 if not set
        if settings.DATA_STALENESS_MAX_MIN is None:
            settings.DATA_STALENESS_MAX_MIN = 30
            print(f"✅ Development mode: DATA_STALENESS_MAX_MIN defaulted to 30")


if __name__ == "__main__":
    # Test configuration
    print("🔧 Testing configuration...")
    print(f"  APP_NAME: {settings.APP_NAME}")
    print(f"  DATA_MODE: {settings.DATA_MODE}")
    print(f"  DATA_STALENESS_MAX_MIN: {settings.DATA_STALENESS_MAX_MIN} minutes")
    print(f"  REQUIRE_MIN_FUND_YEARS: {settings.REQUIRE_MIN_FUND_YEARS}")
    print(f"  DATABASE_URL: {settings.DATABASE_URL}")
    print(f"  JWT_ALGORITHM: {settings.JWT_ALGORITHM}")
    print(f"  JWT_EXPIRATION_HOURS: {settings.JWT_EXPIRATION_HOURS}")

    try:
        validate_settings()
        print("✅ Configuration valid!")
    except ValueError as e:
        print(f"❌ Configuration error: {e}")
