"""
Configuration for FinModAI Backend
Environment-based settings with sensible defaults
"""

from __future__ import annotations
import os
from typing import Optional
from pydantic import BaseModel
from pydantic_settings import BaseSettings


class Settings(BaseSettings):
    """Application settings with environment variable support"""

    # Application
    APP_NAME: str = "FinModAI"
    APP_VERSION: str = "1.0.0"
    DEBUG: bool = False

    # Data Configuration
    data_mode: str = "production"
    data_staleness_max_min: int | None = None  # required in prod
    require_min_fund_years: int = 3

    # JWT Authentication
    JWT_SECRET: str = "test-jwt-secret-for-ci-minimum-32-characters-long"
    JWT_ALGORITHM: str = "HS256"
    JWT_EXPIRATION_HOURS: int = 24

    # Database
    DATABASE_URL: str = "sqlite:///./finmodai.db"

    # Export
    EXPORT_FOOTER_NOTE: str = "Generated by FinModAI • For discussion only • See provenance."

    # API Keys (optional for MVP)
    ALPHAVANTAGE_API_KEY: Optional[str] = None
    FINNHUB_API_KEY: Optional[str] = None
    POLYGON_API_KEY: Optional[str] = None
    ANTHROPIC_API_KEY: Optional[str] = None

    # CORS
    CORS_ORIGINS: list[str] = ["http://localhost:3000", "http://localhost:5000"]

    # File Storage
    UPLOAD_FOLDER: str = "./uploads"
    MAX_UPLOAD_SIZE: int = 16 * 1024 * 1024  # 16MB

    # API Limits
    DEFAULT_SNAPSHOT_LIMIT: int = 100
    MAX_SNAPSHOT_LIMIT: int = 1000
    DEFAULT_LEADERS_LIMIT: int = 3
    MAX_LEADERS_LIMIT: int = 50

    class Config:
        env_file = ".env"
        case_sensitive = True


def _coerce_env():
    """Coerce environment variables into Settings object."""
    dm = os.getenv("DATA_MODE", "production").lower()

    # Handle DATA_STALENESS_MAX_MIN
    staleness_env = os.getenv("DATA_STALENESS_MAX_MIN")
    if staleness_env:
        staleness_val = int(staleness_env)
    else:
        staleness_val = 30 if dm != "production" else None

    s = Settings(
        data_mode=dm,
        data_staleness_max_min=staleness_val,
        require_min_fund_years=int(os.getenv("REQUIRE_MIN_FUND_YEARS", "3")),
        JWT_SECRET=os.getenv("JWT_SECRET", "test-jwt-secret-for-ci-minimum-32-characters-long"),
        DEBUG=os.getenv("DEBUG", "False").lower() == "true",
        DATABASE_URL=os.getenv("DATABASE_URL", "sqlite:///./finmodai.db"),
        ALPHAVANTAGE_API_KEY=REDACTED
        FINNHUB_API_KEY=os.getenv("FINNHUB_API_KEY"),
        POLYGON_API_KEY=REDACTED
        ANTHROPIC_API_KEY=os.getenv("ANTHROPIC_API_KEY"),
    )
    return s


settings = _coerce_env()


def validate_settings() -> None:
    """Validate critical settings at startup"""
    if settings.data_mode == "production":
        # Ensure JWT secret is set in production
        if not settings.JWT_SECRET or len(settings.JWT_SECRET) < 32:
            raise ValueError("JWT_SECRET must be at least 32 characters in production mode")

        # Ensure DATA_STALENESS_MAX_MIN is explicitly set in production
        if settings.data_staleness_max_min is None:
            raise RuntimeError("Required env var DATA_STALENESS_MAX_MIN is not set for production.")

        print("✅ Production mode: Dummy data blocked")
    else:
        # In dev/test, default to 30 if not set
        if settings.data_staleness_max_min is None:
            settings.data_staleness_max_min = 30
            print(f"✅ Development mode: DATA_STALENESS_MAX_MIN defaulted to 30")


# Back-compat alias used by some modules/tests
class _CompatConfig(BaseModel):
    DATA_MODE: str = settings.data_mode
    DATA_STALENESS_MAX_MIN: int | None = settings.data_staleness_max_min
    REQUIRE_MIN_FUND_YEARS: int = settings.require_min_fund_years
    DEFAULT_SNAPSHOT_LIMIT: int = settings.DEFAULT_SNAPSHOT_LIMIT
    MAX_SNAPSHOT_LIMIT: int = settings.MAX_SNAPSHOT_LIMIT
    DEFAULT_LEADERS_LIMIT: int = settings.DEFAULT_LEADERS_LIMIT
    MAX_LEADERS_LIMIT: int = settings.MAX_LEADERS_LIMIT


config = _CompatConfig()


if __name__ == "__main__":
    # Test configuration
    print("🔧 Testing configuration...")
    print(f"  APP_NAME: {settings.APP_NAME}")
    print(f"  DATA_MODE: {settings.data_mode}")
    print(f"  DATA_STALENESS_MAX_MIN: {settings.data_staleness_max_min} minutes")
    print(f"  REQUIRE_MIN_FUND_YEARS: {settings.require_min_fund_years}")
    print(f"  DATABASE_URL: {settings.DATABASE_URL}")
    print(f"  JWT_ALGORITHM: {settings.JWT_ALGORITHM}")
    print(f"  JWT_EXPIRATION_HOURS: {settings.JWT_EXPIRATION_HOURS}")

    try:
        validate_settings()
        print("✅ Configuration valid!")
    except ValueError as e:
        print(f"❌ Configuration error: {e}")
