#!/bin/bash
# FinModAI Backend Setup Script
# This script ensures everything is ready to run

set -e  # Exit on error

echo "🚀 FinModAI Backend Setup"
echo "=========================="
echo ""

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# Check Python version
echo "📋 Checking Python version..."
python_version=$(python3 --version 2>&1 | awk '{print $2}')
echo "   Python version: $python_version"

if [[ $(echo "$python_version 3.11" | awk '{print ($1 >= $2)}') == "1" ]]; then
    echo -e "   ${GREEN}✅ Python version OK${NC}"
else
    echo -e "   ${YELLOW}⚠️  Python 3.11+ recommended${NC}"
fi
echo ""

# Create virtual environment
echo "📦 Creating virtual environment..."
if [ ! -d "venv" ]; then
    python3 -m venv venv
    echo -e "   ${GREEN}✅ Virtual environment created${NC}"
else
    echo -e "   ${YELLOW}⚠️  Virtual environment already exists${NC}"
fi
echo ""

# Activate virtual environment
echo "🔧 Activating virtual environment..."
source venv/bin/activate
echo -e "   ${GREEN}✅ Virtual environment activated${NC}"
echo ""

# Upgrade pip
echo "⬆️  Upgrading pip..."
pip install --upgrade pip > /dev/null 2>&1
echo -e "   ${GREEN}✅ pip upgraded${NC}"
echo ""

# Install dependencies
echo "📥 Installing dependencies..."
pip install -r requirements.txt
echo -e "   ${GREEN}✅ Dependencies installed${NC}"
echo ""

# Create .env file if it doesn't exist
echo "📝 Checking environment variables..."
if [ ! -f ".env" ]; then
    echo "   Creating .env file..."
    cat > .env << EOF
# FinModAI Environment Variables

# Required
JWT_SECRET=$(python3 -c "import secrets; print(secrets.token_urlsafe(32))")

# Database
DATABASE_URL=sqlite:///./finmodai.db

# Production
DATA_MODE=production
DEBUG=True
DATA_STALENESS_MAX_MIN=30
REQUIRE_MIN_FUND_YEARS=3

# API Keys (add your keys here)
# ALPHAVANTAGE_API_KEY=your_key_here
# FINNHUB_API_KEY=your_key_here
# POLYGON_API_KEY=your_key_here

# CORS
CORS_ORIGINS=["http://localhost:3000","http://localhost:5000"]

# Export
EXPORT_FOOTER_NOTE="Generated by FinModAI • For discussion only • See provenance."
EOF
    echo -e "   ${GREEN}✅ .env file created${NC}"
else
    echo -e "   ${YELLOW}⚠️  .env file already exists${NC}"
fi
echo ""

# Create necessary directories
echo "📁 Creating directories..."
mkdir -p exports
mkdir -p uploads
echo -e "   ${GREEN}✅ Directories created${NC}"
echo ""

# Initialize database
echo "🗄️  Initializing database..."
python3 -c "from persistence.database import init_db; init_db(); print('Database initialized successfully')"
echo -e "   ${GREEN}✅ Database initialized${NC}"
echo ""

# Run tests
echo "🧪 Running tests..."
if pytest tests/ -v --tb=short 2>&1 | tee test_output.log; then
    echo -e "   ${GREEN}✅ All tests passed${NC}"
else
    echo -e "   ${YELLOW}⚠️  Some tests failed (check test_output.log)${NC}"
fi
echo ""

# Check configuration
echo "⚙️  Checking configuration..."
python3 -c "from config import settings; print(f'✅ Configuration valid: {settings.APP_NAME} v{settings.APP_VERSION}')"
echo ""

# Final checks
echo "🔍 Final checks..."
echo "   Checking imports..."

if python3 -c "import fastapi; import uvicorn; import sqlalchemy; import xlsxwriter; import weasyprint; import reportlab; import jwt; import passlib; print('✅ All critical imports OK')"; then
    echo -e "   ${GREEN}✅ All critical imports OK${NC}"
else
    echo -e "   ${RED}❌ Some imports failed${NC}"
    exit 1
fi
echo ""

# Success message
echo "=========================="
echo -e "${GREEN}✅ Setup Complete!${NC}"
echo "=========================="
echo ""
echo "🚀 To start the server:"
echo "   1. Activate virtual environment: source venv/bin/activate"
echo "   2. Run: python app.py"
echo "   3. Open: http://localhost:8000/api/docs"
echo ""
echo "📚 Documentation:"
echo "   - API Docs: http://localhost:8000/api/docs"
echo "   - Health: http://localhost:8000/health"
echo ""
echo "🎉 Ready to go!"

