/**
 * Trading Comps Model Types
 * 
 * Real comparable company analysis using peer multiples only.
 * No DCF assumptions (WACC, terminal growth, etc.).
 */

export type Percentiles = {
  min: number;
  p25: number;
  median: number;
  mean: number;
  p75: number;
  max: number;
};

export type CompanyFinancials = {
  name: string;
  ticker: string;
  marketCap: number;           // $ millions
  enterpriseValue: number;     // $ millions
  revenue: number;             // LTM Revenue ($ millions)
  ebitda: number;              // LTM EBITDA ($ millions)
  ebit: number;                // LTM EBIT ($ millions)
  netIncome: number;           // LTM Net Income ($ millions)
  shares: number;              // Shares outstanding (millions)
  price: number;               // Price per share
  netDebt: number;             // Total debt - cash ($ millions)
  
  // Computed multiples
  evToRevenue: number;
  evToEbitda: number;
  evToEbit: number;
  pe: number;
  
  // Source tracking
  source: 'auto' | 'custom';
  aiEstimated?: string[];      // List of fields estimated by AI
};

export type TargetCompany = {
  ticker: string;
  name: string;
  revenue: number;
  ebitda: number;
  ebit: number;
  netIncome: number;
  shares: number;
  netDebt: number;
  price?: number;              // Current price (optional)
};

export type CompsStatistics = {
  evRevenue: Percentiles;
  evEbitda: Percentiles;
  evEbit: Percentiles;
  pe: Percentiles;
};

export type ImpliedValuation = {
  // Using median multiples
  evRevenueMedian: number;     // EV from Revenue × median multiple
  evEbitdaMedian: number;      // EV from EBITDA × median multiple
  evEbitMedian: number;        // EV from EBIT × median multiple
  peMedian: number;            // Market cap from NI × median P/E
  
  // Using mean multiples
  evRevenueMean: number;
  evEbitdaMean: number;
  evEbitMean: number;
  peMean: number;
  
  // Implied equity value per share
  pricePerShareMedian: number;
  pricePerShareMean: number;
  blendedValuePerShare: number; // Average of all methods
  
  // Upside/downside vs current price
  upsideDownside?: string;
};

export type CompsModel = {
  target: TargetCompany;
  comps: CompanyFinancials[];
  stats: CompsStatistics;
  impliedValuation: ImpliedValuation;
  commentary: string;
  metadata: {
    autoGenerated: number;     // Count of auto-generated peers
    customProvided: number;    // Count of custom peers
    aiEstimatedCount: number;  // Count of companies with AI estimates
  };
};

/**
 * Request type for generating comps model
 */
export type CompsModelRequest = {
  ticker: string;
  companyName?: string;
  sector?: string;
  
  // Optional custom comparables
  customComps?: string[];      // Array of ticker symbols
  useOnlyCustom?: boolean;     // If true, use ONLY custom comps
  
  // Optional target financials (if not fetched from API)
  targetRevenue?: number;
  targetEbitda?: number;
  targetEbit?: number;
  targetNetIncome?: number;
  targetShares?: number;
  targetNetDebt?: number;
  targetPrice?: number;
};

/**
 * Partial financials before enrichment
 */
export type PartialCompanyFinancials = {
  name?: string;
  ticker: string;
  marketCap?: number | null;
  enterpriseValue?: number | null;
  revenue?: number | null;
  ebitda?: number | null;
  ebit?: number | null;
  netIncome?: number | null;
  shares?: number | null;
  price?: number | null;
  netDebt?: number | null;
  source: 'auto' | 'custom';
};

/**
 * Request to OpenAI for financial data enrichment
 */
export type FinancialEnrichmentRequest = {
  ticker: string;
  companyName?: string;
  sector?: string;
  partialFinancials: PartialCompanyFinancials;
  peerMedians?: {
    revenue?: number;
    ebitda?: number;
    ebit?: number;
    netIncome?: number;
    marketCap?: number;
  };
};

