export const APP_NAME = 'CapitalBase';
export const APP_WORKSPACE_NAME = 'CapitalBase Workspace';
export const APP_CONSOLE_NAME = 'Command Center';
export const APP_DASHBOARD_TITLE = 'Analyst Home';
export const APP_DASHBOARD_TAGLINE = 'Finance infrastructure for builders, bankers, and buy-side teams.';
export const APP_WORKSPACE_FOOTER = 'Generated by CapitalBase • For discussion only • See provenance.';
