/**
 * Comps Calculator
 * 
 * Calculates trading multiples, statistics, and implied valuations.
 */

import type {
  CompanyFinancials,
  TargetCompany,
  Percentiles,
  CompsStatistics,
  ImpliedValuation,
  CompsModel,
} from '@/types/compsModel';

/**
 * Calculate percentiles for a set of values
 */
export function calculatePercentiles(values: number[]): Percentiles {
  if (values.length === 0) {
    return { min: 0, p25: 0, median: 0, mean: 0, p75: 0, max: 0 };
  }

  // Filter out invalid values
  const valid = values.filter(v => !isNaN(v) && isFinite(v) && v > 0);
  
  if (valid.length === 0) {
    return { min: 0, p25: 0, median: 0, mean: 0, p75: 0, max: 0 };
  }

  const sorted = [...valid].sort((a, b) => a - b);
  const n = sorted.length;

  const min = sorted[0];
  const max = sorted[n - 1];
  const mean = sorted.reduce((a, b) => a + b, 0) / n;

  const p25Index = Math.floor(n * 0.25);
  const medianIndex = Math.floor(n * 0.50);
  const p75Index = Math.floor(n * 0.75);

  const p25 = sorted[p25Index];
  const median = n % 2 === 0 && medianIndex > 0
    ? (sorted[medianIndex - 1] + sorted[medianIndex]) / 2
    : sorted[medianIndex];
  const p75 = sorted[p75Index];

  return { min, p25, median, mean, p75, max };
}

/**
 * Calculate statistics for all multiples
 */
export function calculateCompsStatistics(comps: CompanyFinancials[]): CompsStatistics {
  const evRevenue = comps.map(c => c.evToRevenue);
  const evEbitda = comps.map(c => c.evToEbitda);
  const evEbit = comps.map(c => c.evToEbit);
  const pe = comps.map(c => c.pe);

  return {
    evRevenue: calculatePercentiles(evRevenue),
    evEbitda: calculatePercentiles(evEbitda),
    evEbit: calculatePercentiles(evEbit),
    pe: calculatePercentiles(pe),
  };
}

/**
 * Calculate implied valuation for target company
 */
export function calculateImpliedValuation(
  target: TargetCompany,
  stats: CompsStatistics
): ImpliedValuation {
  // Using median multiples
  const evRevenueMedian = target.revenue * stats.evRevenue.median;
  const evEbitdaMedian = target.ebitda * stats.evEbitda.median;
  const evEbitMedian = target.ebit * stats.evEbit.median;
  const marketCapPeMedian = target.netIncome * stats.pe.median;

  // Using mean multiples
  const evRevenueMean = target.revenue * stats.evRevenue.mean;
  const evEbitdaMean = target.ebitda * stats.evEbitda.mean;
  const evEbitMean = target.ebit * stats.evEbit.mean;
  const marketCapPeMean = target.netIncome * stats.pe.mean;

  // Convert EV to equity value per share (using median)
  const equityValueRevenueMedian = evRevenueMedian - target.netDebt;
  const equityValueEbitdaMedian = evEbitdaMedian - target.netDebt;
  const equityValueEbitMedian = evEbitMedian - target.netDebt;
  const equityValuePeMedian = marketCapPeMedian; // P/E already gives market cap

  const priceRevenueMedian = equityValueRevenueMedian / target.shares;
  const priceEbitdaMedian = equityValueEbitdaMedian / target.shares;
  const priceEbitMedian = equityValueEbitMedian / target.shares;
  const pricePeMedian = equityValuePeMedian / target.shares;

  // Convert EV to equity value per share (using mean)
  const equityValueRevenueMean = evRevenueMean - target.netDebt;
  const equityValueEbitdaMean = evEbitdaMean - target.netDebt;
  const equityValueEbitMean = evEbitMean - target.netDebt;
  const equityValuePeMean = marketCapPeMean;

  const priceRevenueMean = equityValueRevenueMean / target.shares;
  const priceEbitdaMean = equityValueEbitdaMean / target.shares;
  const priceEbitMean = equityValueEbitMean / target.shares;
  const pricePeMean = equityValuePeMean / target.shares;

  // Blended value (average of all methods)
  const pricePerShareMedian = (priceRevenueMedian + priceEbitdaMedian + priceEbitMedian + pricePeMedian) / 4;
  const pricePerShareMean = (priceRevenueMean + priceEbitdaMean + priceEbitMean + pricePeMean) / 4;
  const blendedValuePerShare = (pricePerShareMedian + pricePerShareMean) / 2;

  // Calculate upside/downside vs current price
  let upsideDownside: string | undefined;
  if (target.price) {
    const pctChange = ((blendedValuePerShare - target.price) / target.price) * 100;
    const sign = pctChange >= 0 ? '+' : '';
    upsideDownside = `${sign}${pctChange.toFixed(1)}%`;
  }

  return {
    evRevenueMedian,
    evEbitdaMedian,
    evEbitMedian,
    peMedian: marketCapPeMedian,
    evRevenueMean,
    evEbitdaMean,
    evEbitMean,
    peMean: marketCapPeMean,
    pricePerShareMedian,
    pricePerShareMean,
    blendedValuePerShare,
    upsideDownside,
  };
}

/**
 * Generate commentary for comps analysis
 */
export function generateCompsCommentary(
  target: TargetCompany,
  comps: CompanyFinancials[],
  stats: CompsStatistics,
  impliedValuation: ImpliedValuation,
  metadata: { autoGenerated: number; customProvided: number; aiEstimatedCount: number }
): string {
  const autoCount = metadata.autoGenerated;
  const customCount = metadata.customProvided;
  const aiCount = metadata.aiEstimatedCount;

  const peerSetDesc = customCount > 0
    ? `${comps.length} comparable companies (${customCount} custom, ${autoCount} auto-generated)`
    : `${comps.length} comparable companies`;

  const medianEvRevenue = stats.evRevenue.median.toFixed(2);
  const medianEvEbitda = stats.evEbitda.median.toFixed(1);
  const medianPe = stats.pe.median.toFixed(1);

  const impliedPrice = impliedValuation.blendedValuePerShare.toFixed(2);
  const upsideText = impliedValuation.upsideDownside
    ? ` representing ${impliedValuation.upsideDownside} vs current price`
    : '';

  const aiEstimateNote = aiCount > 0
    ? ` Note: ${aiCount} companies had missing financial data that was estimated using AI based on peer medians and sector norms.`
    : '';

  return `${target.ticker} trading comps analysis based on ${peerSetDesc}. ` +
    `Peer median multiples: ${medianEvRevenue}x EV/Revenue, ${medianEvEbitda}x EV/EBITDA, ${medianPe}x P/E. ` +
    `Applying these multiples to ${target.ticker}'s LTM financials (Revenue: $${(target.revenue / 1000).toFixed(1)}B, ` +
    `EBITDA: $${(target.ebitda / 1000).toFixed(1)}B) implies a blended equity value of $${impliedPrice} per share${upsideText}. ` +
    `The analysis suggests ${target.ticker} is trading ${impliedValuation.upsideDownside?.startsWith('+') ? 'below' : 'above'} ` +
    `peer median valuations.${aiEstimateNote}`;
}

/**
 * Build complete comps model
 */
export function buildCompsModel(
  target: TargetCompany,
  comps: CompanyFinancials[]
): CompsModel {
  const stats = calculateCompsStatistics(comps);
  const impliedValuation = calculateImpliedValuation(target, stats);

  const autoGenerated = comps.filter(c => c.source === 'auto').length;
  const customProvided = comps.filter(c => c.source === 'custom').length;
  const aiEstimatedCount = comps.filter(c => c.aiEstimated && c.aiEstimated.length > 0).length;

  const metadata = {
    autoGenerated,
    customProvided,
    aiEstimatedCount,
  };

  const commentary = generateCompsCommentary(target, comps, stats, impliedValuation, metadata);

  return {
    target,
    comps,
    stats,
    impliedValuation,
    commentary,
    metadata,
  };
}

