export const DEMO_TICKERS = [
  'AAPL',
  'MSFT',
  'NVDA',
  'AMZN',
  'GOOGL',
  'META',
  'TSLA',
  'JPM',
  'XOM',
  'UNH',
  'V',
  'MA',
  'AVGO',
  'COST',
  'PEP',
  'KO',
  'WMT',
  'DIS',
  'NFLX',
  'ORCL',
  'CRM',
  'ADBE',
  'INTU',
  'NOW',
  'IBM',
  'CSCO',
  'QCOM',
  'TXN',
  'AMD',
  'INTC',
  'AMAT',
  'MU',
  'LRCX',
  'ADI',
  'PANW',
  'CRWD',
  'SNOW',
  'SHOP',
  'UBER',
  'ABNB',
  'BKNG',
  'CMG',
  'MCD',
  'SBUX',
  'NKE',
  'HD',
  'LOW',
  'CAT',
  'DE',
  'HON',
  'GE',
  'RTX',
  'BA',
  'GS',
  'MS',
  'BLK',
  'SCHW',
  'AXP',
  'BAC',
  'C',
  'PGR',
  'BRK.B',
  'LLY',
  'JNJ',
  'PFE',
  'MRK',
  'ABBV',
  'TMO',
  'ISRG',
  'DHR',
  'MDT',
  'CVX',
  'SLB',
  'COP',
  'LIN',
  'APD',
  'SHW',
  'PLD',
  'SPG',
  'VZ',
  'T',
  'TMUS',
];

export const DEMO_COMPANY_META: Record<string, { name: string; sector: string }> = {
  AAPL: { name: 'Apple Inc.', sector: 'Technology' },
  MSFT: { name: 'Microsoft Corporation', sector: 'Technology' },
  NVDA: { name: 'NVIDIA Corporation', sector: 'Technology' },
  AMZN: { name: 'Amazon.com, Inc.', sector: 'Consumer Discretionary' },
  GOOGL: { name: 'Alphabet Inc.', sector: 'Communication Services' },
  META: { name: 'Meta Platforms, Inc.', sector: 'Communication Services' },
  TSLA: { name: 'Tesla, Inc.', sector: 'Consumer Discretionary' },
  JPM: { name: 'JPMorgan Chase & Co.', sector: 'Financials' },
  XOM: { name: 'Exxon Mobil Corporation', sector: 'Energy' },
  UNH: { name: 'UnitedHealth Group Incorporated', sector: 'Health Care' },
  V: { name: 'Visa Inc.', sector: 'Financials' },
  MA: { name: 'Mastercard Incorporated', sector: 'Financials' },
  AVGO: { name: 'Broadcom Inc.', sector: 'Technology' },
  COST: { name: 'Costco Wholesale Corporation', sector: 'Consumer Staples' },
  PEP: { name: 'PepsiCo, Inc.', sector: 'Consumer Staples' },
  KO: { name: 'The Coca-Cola Company', sector: 'Consumer Staples' },
  WMT: { name: 'Walmart Inc.', sector: 'Consumer Staples' },
  DIS: { name: 'The Walt Disney Company', sector: 'Communication Services' },
  NFLX: { name: 'Netflix, Inc.', sector: 'Communication Services' },
  ORCL: { name: 'Oracle Corporation', sector: 'Technology' },
  CRM: { name: 'Salesforce, Inc.', sector: 'Technology' },
  ADBE: { name: 'Adobe Inc.', sector: 'Technology' },
  INTU: { name: 'Intuit Inc.', sector: 'Technology' },
  NOW: { name: 'ServiceNow, Inc.', sector: 'Technology' },
  IBM: { name: 'International Business Machines Corporation', sector: 'Technology' },
  CSCO: { name: 'Cisco Systems, Inc.', sector: 'Technology' },
  QCOM: { name: 'QUALCOMM Incorporated', sector: 'Technology' },
  TXN: { name: 'Texas Instruments Incorporated', sector: 'Technology' },
  AMD: { name: 'Advanced Micro Devices, Inc.', sector: 'Technology' },
  INTC: { name: 'Intel Corporation', sector: 'Technology' },
  AMAT: { name: 'Applied Materials, Inc.', sector: 'Technology' },
  MU: { name: 'Micron Technology, Inc.', sector: 'Technology' },
  LRCX: { name: 'Lam Research Corporation', sector: 'Technology' },
  ADI: { name: 'Analog Devices, Inc.', sector: 'Technology' },
  PANW: { name: 'Palo Alto Networks, Inc.', sector: 'Technology' },
  CRWD: { name: 'CrowdStrike Holdings, Inc.', sector: 'Technology' },
  SNOW: { name: 'Snowflake Inc.', sector: 'Technology' },
  SHOP: { name: 'Shopify Inc.', sector: 'Technology' },
  UBER: { name: 'Uber Technologies, Inc.', sector: 'Industrials' },
  ABNB: { name: 'Airbnb, Inc.', sector: 'Consumer Discretionary' },
  BKNG: { name: 'Booking Holdings Inc.', sector: 'Consumer Discretionary' },
  CMG: { name: 'Chipotle Mexican Grill, Inc.', sector: 'Consumer Discretionary' },
  MCD: { name: "McDonald's Corporation", sector: 'Consumer Discretionary' },
  SBUX: { name: 'Starbucks Corporation', sector: 'Consumer Discretionary' },
  NKE: { name: 'NIKE, Inc.', sector: 'Consumer Discretionary' },
  HD: { name: 'The Home Depot, Inc.', sector: 'Consumer Discretionary' },
  LOW: { name: "Lowe's Companies, Inc.", sector: 'Consumer Discretionary' },
  CAT: { name: 'Caterpillar Inc.', sector: 'Industrials' },
  DE: { name: 'Deere & Company', sector: 'Industrials' },
  HON: { name: 'Honeywell International Inc.', sector: 'Industrials' },
  GE: { name: 'GE Aerospace', sector: 'Industrials' },
  RTX: { name: 'RTX Corporation', sector: 'Industrials' },
  BA: { name: 'The Boeing Company', sector: 'Industrials' },
  GS: { name: 'The Goldman Sachs Group, Inc.', sector: 'Financials' },
  MS: { name: 'Morgan Stanley', sector: 'Financials' },
  BLK: { name: 'BlackRock, Inc.', sector: 'Financials' },
  SCHW: { name: 'The Charles Schwab Corporation', sector: 'Financials' },
  AXP: { name: 'American Express Company', sector: 'Financials' },
  BAC: { name: 'Bank of America Corporation', sector: 'Financials' },
  C: { name: 'Citigroup Inc.', sector: 'Financials' },
  PGR: { name: 'The Progressive Corporation', sector: 'Financials' },
  'BRK.B': { name: 'Berkshire Hathaway Inc. Class B', sector: 'Financials' },
  LLY: { name: 'Eli Lilly and Company', sector: 'Health Care' },
  JNJ: { name: 'Johnson & Johnson', sector: 'Health Care' },
  PFE: { name: 'Pfizer Inc.', sector: 'Health Care' },
  MRK: { name: 'Merck & Co., Inc.', sector: 'Health Care' },
  ABBV: { name: 'AbbVie Inc.', sector: 'Health Care' },
  TMO: { name: 'Thermo Fisher Scientific Inc.', sector: 'Health Care' },
  ISRG: { name: 'Intuitive Surgical, Inc.', sector: 'Health Care' },
  DHR: { name: 'Danaher Corporation', sector: 'Health Care' },
  MDT: { name: 'Medtronic plc', sector: 'Health Care' },
  CVX: { name: 'Chevron Corporation', sector: 'Energy' },
  SLB: { name: 'SLB', sector: 'Energy' },
  COP: { name: 'ConocoPhillips', sector: 'Energy' },
  LIN: { name: 'Linde plc', sector: 'Materials' },
  APD: { name: 'Air Products and Chemicals, Inc.', sector: 'Materials' },
  SHW: { name: 'The Sherwin-Williams Company', sector: 'Materials' },
  PLD: { name: 'Prologis, Inc.', sector: 'Real Estate' },
  SPG: { name: 'Simon Property Group, Inc.', sector: 'Real Estate' },
  VZ: { name: 'Verizon Communications Inc.', sector: 'Communication Services' },
  T: { name: 'AT&T Inc.', sector: 'Communication Services' },
  TMUS: { name: 'T-Mobile US, Inc.', sector: 'Communication Services' },
};

export function isDemoTicker(ticker: string): boolean {
  return DEMO_TICKERS.includes(ticker.toUpperCase());
}
