'use client';

import { useEffect, useState, useCallback, useRef } from 'react';
import Link from 'next/link';
import { Button } from '@/components/ui/button';
import { DownloadModelButton } from '@/components/models/DownloadButton';
import { Home, Plus, Loader2 } from 'lucide-react';
import { APP_NAME } from '@/lib/branding';

type Model = {
  id: string;
  ticker: string;
  type?: string | null;
  model_type?: string | null;
  status: string;
  created_at: string;
  file_name: string | null;
};

export default function ModelsPage() {
  const [models, setModels] = useState<Model[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const hasFetchedRef = useRef(false);

  const fetchModels = useCallback(async () => {
    if (hasFetchedRef.current && models.length > 0) {
      return;
    }

    try {
      console.time('[ModelsPage] fetchModels');
      setLoading(true);
      setError(null);
      
      const { listAllModels } = await import('@/lib/modelsRepo');
      const data = await listAllModels();
      setModels(data);
      hasFetchedRef.current = true;
    } catch (err) {
      console.error('Failed to fetch models:', err);
      setError('Failed to load models. Please try again.');
      setModels([]);
    } finally {
      setLoading(false);
      console.timeEnd('[ModelsPage] fetchModels');
    }
  }, [models.length]);

  useEffect(() => {
    if (!hasFetchedRef.current) {
      fetchModels();
    }
  }, [fetchModels]);

  return (
    <main className="min-h-screen bg-gradient-to-b from-black via-slate-950 to-black px-6 py-10">
      <div className="mx-auto max-w-6xl space-y-8">
        <div className="flex items-center gap-3">
          <Button asChild variant="ghost" size="sm">
            <Link href="/app">
              <Home className="mr-2 h-4 w-4" />
              Home
            </Link>
          </Button>
        </div>

        <header className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
          <div>
            <p className="text-sm font-semibold uppercase tracking-wide text-emerald-500">{APP_NAME}</p>
            <h1 className="text-3xl font-semibold text-white">Model Library</h1>
            <p className="text-sm text-slate-400">
              Track every workbook generated by the command center.
            </p>
          </div>
          <Button asChild>
            <Link href="/models/create">
              <Plus className="mr-2 h-4 w-4" />
              Create Model
            </Link>
          </Button>
        </header>

        {loading ? (
          <div className="flex items-center justify-center rounded-2xl border border-white/5 bg-slate-950/60 backdrop-blur-sm p-12">
            <div className="text-center">
              <Loader2 className="mx-auto h-8 w-8 animate-spin text-emerald-500" />
              <p className="mt-3 text-sm text-slate-400">Loading models...</p>
            </div>
          </div>
        ) : error ? (
          <div className="rounded-2xl border border-rose-500/20 bg-slate-950/60 backdrop-blur-sm p-6">
            <p className="font-semibold text-rose-400">Error</p>
            <p className="mt-1 text-sm text-slate-400">{error}</p>
            <Button onClick={fetchModels} variant="outline" size="sm" className="mt-4 bg-emerald-500 text-black hover:bg-emerald-400 border-0">
              Try Again
            </Button>
          </div>
        ) : (
          <section className="rounded-2xl border border-white/5 bg-slate-950/60 backdrop-blur-sm p-6">
            <div className="overflow-x-auto">
              <table className="min-w-full text-sm text-slate-300">
                <thead className="bg-slate-900/40 text-slate-400">
                  <tr className="text-left text-xs uppercase tracking-wide">
                    <th className="pb-2 font-semibold">Ticker</th>
                    <th className="pb-2 font-semibold">Type</th>
                    <th className="pb-2 font-semibold">Created</th>
                    <th className="pb-2 font-semibold">Status</th>
                    <th className="pb-2 text-right font-semibold">Actions</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-white/5">
                  {models.map((model) => {
                    const resolvedType = model.model_type ?? model.type ?? 'dcf';
                    return (
                      <tr
                        key={model.id}
                        className="transition hover:bg-slate-900/40"
                      >
                        <td className="py-3 font-semibold text-white">{model.ticker}</td>
                        <td className="py-3 text-slate-300">{formatModelLabel(resolvedType)}</td>
                        <td className="py-3 text-slate-400">
                          {new Date(model.created_at).toLocaleDateString('en-US', {
                            month: 'short',
                            day: 'numeric',
                            year: 'numeric',
                            hour: '2-digit',
                            minute: '2-digit'
                          })}
                        </td>
                        <td className="py-3">
                          <span
                            className={`rounded-full border px-2 py-0.5 text-xs uppercase tracking-wide ${
                              model.status === 'ready'
                                ? 'border-emerald-500/30 bg-emerald-500/10 text-emerald-400'
                                : model.status === 'generating'
                                ? 'border-blue-500/30 bg-blue-500/10 text-blue-400'
                                : 'border-rose-500/30 bg-rose-500/10 text-rose-400'
                            }`}
                          >
                            {model.status}
                          </span>
                        </td>
                        <td className="py-3">
                          <div className="flex items-center justify-end gap-2">
                            <Button asChild size="sm" variant="ghost">
                              <Link href={`/models/${model.id}`}>View</Link>
                            </Button>
                            <DownloadModelButton
                              ticker={model.ticker}
                              modelType={resolvedType}
                              modelId={model.id}
                              disabled={!(model.status === 'ready' && model.file_name)}
                            />
                          </div>
                        </td>
                      </tr>
                    );
                  })}
                  {models.length === 0 && (
                    <tr>
                      <td colSpan={5} className="py-12 text-center">
                        <div className="mx-auto max-w-sm">
                          <p className="font-semibold text-[var(--cb-text-secondary)]">No models yet</p>
                          <p className="mt-1 text-sm text-[var(--cb-text-muted)]">
                            Create your first financial model to see it here.
                          </p>
                          <Button asChild className="mt-4" size="sm">
                            <Link href="/models/create">
                              <Plus className="mr-2 h-4 w-4" />
                              Create Your First Model
                            </Link>
                          </Button>
                        </div>
                      </td>
                    </tr>
                  )}
                </tbody>
              </table>
            </div>
          </section>
        )}
      </div>
    </main>
  );
}

function formatModelLabel(type: string) {
  switch (type) {
    case 'three-statement':
      return 'Three-Statement';
    case 'dcf':
      return 'DCF';
    case 'lbo':
      return 'LBO';
    case 'comps':
      return 'Comps';
    default:
      return type;
  }
}
