'use client';

import { useEffect, useState } from 'react';
import Link from 'next/link';
import { Button } from '@/components/ui/button';
import { DownloadModelButton } from '@/components/models/DownloadButton';
import { Home, Plus, Loader2 } from 'lucide-react';
import { APP_NAME } from '@/lib/branding';

type Model = {
  id: string;
  ticker: string;
  type: string;
  status: string;
  created_at: string;
};

export default function ModelsPage() {
  const [models, setModels] = useState<Model[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    fetchModels();
  }, []);

  const fetchModels = async () => {
    try {
      setLoading(true);
      setError(null);
      
      // Import the function directly to avoid API route
      const { listAllModels } = await import('@/lib/modelsRepo');
      const data = await listAllModels();
      setModels(data);
    } catch (err) {
      console.error('Failed to fetch models:', err);
      setError('Failed to load models. Please try again.');
      setModels([]);
    } finally {
      setLoading(false);
    }
  };

  return (
    <main className="min-h-screen bg-[var(--cb-bg)] px-6 py-10 text-[var(--cb-text-body)]">
      <div className="mx-auto max-w-6xl space-y-8">
        {/* Navigation */}
        <div className="flex items-center gap-3">
          <Button asChild variant="ghost" size="sm">
            <Link href="/app">
              <Home className="mr-2 h-4 w-4" />
              Home
            </Link>
          </Button>
        </div>

        <header className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
          <div>
            <p className="text-sm font-semibold uppercase tracking-wide text-[var(--cb-green)]">{APP_NAME}</p>
            <h1 className="text-3xl font-semibold text-[var(--cb-text-primary)]">Model Library</h1>
            <p className="text-sm text-[var(--cb-text-secondary)]">
              Track every workbook generated by the command center.
            </p>
          </div>
          <Button asChild>
            <Link href="/models/create">
              <Plus className="mr-2 h-4 w-4" />
              Create Model
            </Link>
          </Button>
        </header>

        {loading ? (
          <div className="flex items-center justify-center rounded-2xl border border-[var(--cb-border-subtle)] bg-[var(--cb-surface)] p-12 shadow-sm">
            <div className="text-center">
              <Loader2 className="mx-auto h-8 w-8 animate-spin text-primary" />
              <p className="mt-3 text-sm text-[var(--cb-text-muted)]">Loading models...</p>
            </div>
          </div>
        ) : error ? (
          <div className="rounded-2xl border border-red-200 bg-red-50 p-6 shadow-sm">
            <p className="font-semibold text-red-700">Error</p>
            <p className="mt-1 text-sm text-red-600">{error}</p>
            <Button onClick={fetchModels} variant="outline" size="sm" className="mt-4">
              Try Again
            </Button>
          </div>
        ) : (
          <section className="rounded-2xl border border-[var(--cb-border-subtle)] bg-[var(--cb-surface)] p-6 shadow-sm">
            <div className="overflow-x-auto">
              <table className="min-w-full text-sm text-[var(--cb-text-body)]">
                <thead className="bg-[var(--cb-surface-alt)] text-[var(--cb-text-secondary)]">
                  <tr className="text-left text-xs uppercase tracking-wide">
                    <th className="pb-2 font-semibold">Ticker</th>
                    <th className="pb-2 font-semibold">Type</th>
                    <th className="pb-2 font-semibold">Created</th>
                    <th className="pb-2 font-semibold">Status</th>
                    <th className="pb-2 text-right font-semibold">Actions</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-[var(--cb-border-subtle)]">
                  {models.map((model) => (
                    <tr
                      key={model.id}
                      className="transition hover:bg-[var(--cb-surface-alt)]/60"
                    >
                      <td className="py-3 font-semibold">{model.ticker}</td>
                      <td className="py-3">{formatModelLabel(model.type)}</td>
                      <td className="py-3 text-[var(--cb-text-muted)]">
                        {new Date(model.created_at).toLocaleDateString('en-US', {
                          month: 'short',
                          day: 'numeric',
                          year: 'numeric',
                          hour: '2-digit',
                          minute: '2-digit'
                        })}
                      </td>
                      <td className="py-3">
                        <span
                          className={`rounded-full border px-2 py-0.5 text-xs uppercase tracking-wide ${
                            model.status === 'completed'
                              ? 'border-emerald-200 bg-emerald-50 text-emerald-700'
                              : model.status === 'running'
                              ? 'border-sky-200 bg-sky-50 text-sky-700'
                              : 'border-rose-200 bg-rose-50 text-rose-700'
                          }`}
                        >
                          {model.status}
                        </span>
                      </td>
                      <td className="py-3">
                        <div className="flex items-center justify-end gap-2">
                          <Button asChild size="sm" variant="ghost">
                            <Link href={`/models/${model.id}`}>View</Link>
                          </Button>
                          <DownloadModelButton ticker={model.ticker} modelType={model.type} />
                        </div>
                      </td>
                    </tr>
                  ))}
                  {models.length === 0 && (
                    <tr>
                      <td colSpan={5} className="py-12 text-center">
                        <div className="mx-auto max-w-sm">
                          <p className="font-semibold text-[var(--cb-text-secondary)]">No models yet</p>
                          <p className="mt-1 text-sm text-[var(--cb-text-muted)]">
                            Create your first financial model to see it here.
                          </p>
                          <Button asChild className="mt-4" size="sm">
                            <Link href="/models/create">
                              <Plus className="mr-2 h-4 w-4" />
                              Create Your First Model
                            </Link>
                          </Button>
                        </div>
                      </td>
                    </tr>
                  )}
                </tbody>
              </table>
            </div>
          </section>
        )}
      </div>
    </main>
  );
}

function formatModelLabel(type: string) {
  switch (type) {
    case 'three-statement':
      return 'Three-Statement';
    case 'dcf':
      return 'DCF';
    case 'lbo':
      return 'LBO';
    case 'comps':
      return 'Comps';
    default:
      return type;
  }
}
