/**
 * Startups Data - Curated list for demo
 * Last updated: 2024-12-24
 * 
 * Data sources: Public news, funding announcements, industry reports
 * Note: This is a static dataset for demo purposes. Not real-time.
 */

export type StartupSignal = 'Funding' | 'Hiring' | 'Partnerships' | 'Product' | 'Regulation' | 'Competition' | 'Press';

export type StartupSector = 'AI' | 'Fintech' | 'DevTools' | 'Healthcare' | 'Climate' | 'Consumer' | 'Enterprise' | 'Crypto';

export interface Startup {
  id: string;
  name: string;
  sector: StartupSector;
  thesis: string;
  whyTrending: string;
  signals: StartupSignal[];
  momentum: number; // 1-100 score for sorting
  lastUpdated: string;
  sourceHints: string[]; // Generic source types, not specific outlets
}

export interface IPOCandidate {
  id: string;
  name: string;
  sector: StartupSector;
  rumoredTimeframe: string; // e.g., "Q2 2025", "H2 2025"
  lastFundingRound: string; // e.g., "Series F, $500M at $15B valuation"
  publicPeers: string[]; // comparable public companies
  riskNotes: string;
  momentum: number;
  lastUpdated: string;
}

export const STARTUPS: Startup[] = [
  {
    id: 'anthropic',
    name: 'Anthropic',
    sector: 'AI',
    thesis: 'Building safe, steerable AI systems with Claude competing directly against OpenAI.',
    whyTrending: 'Raised $7B+ from Google, Amazon. Claude 3 Opus outperforms GPT-4 on key benchmarks. Enterprise adoption accelerating.',
    signals: ['Funding', 'Product', 'Partnerships', 'Competition'],
    momentum: 98,
    lastUpdated: '2024-12-20',
    sourceHints: ['Public reporting'],
  },
  {
    id: 'stripe',
    name: 'Stripe',
    sector: 'Fintech',
    thesis: 'Payments infrastructure powering internet commerce. Expanding into banking, lending, tax.',
    whyTrending: 'Revenue run-rate >$20B. Stablecoin launch imminent. IPO rumors intensifying for 2025.',
    signals: ['Product', 'Partnerships', 'Press'],
    momentum: 95,
    lastUpdated: '2024-12-18',
    sourceHints: ['Public reporting'],
  },
  {
    id: 'openai',
    name: 'OpenAI',
    sector: 'AI',
    thesis: 'Leading foundation model company. ChatGPT has 100M+ weekly users. Enterprise API revenue scaling.',
    whyTrending: '$86B valuation. GPT-4 Turbo, DALL-E 3, voice mode. Microsoft partnership deepening.',
    signals: ['Funding', 'Product', 'Partnerships', 'Press'],
    momentum: 100,
    lastUpdated: '2024-12-22',
    sourceHints: ['Reuters', 'The Verge'],
  },
  {
    id: 'databricks',
    name: 'Databricks',
    sector: 'Enterprise',
    thesis: 'Unified data and AI platform. Lakehouse architecture replacing data warehouses.',
    whyTrending: '$43B valuation. ARR >$2B. Acquired MosaicML for $1.3B. IPO expected 2025.',
    signals: ['Funding', 'Product', 'Press'],
    momentum: 92,
    lastUpdated: '2024-12-15',
    sourceHints: ['Public reporting'],
  },
  {
    id: 'spacex',
    name: 'SpaceX',
    sector: 'Enterprise',
    thesis: 'Reusable rockets, Starlink satellite internet, Mars colonization. Vertical integration at scale.',
    whyTrending: '$180B valuation. Starship testing progressing. Starlink profitable. 80+ launches in 2024.',
    signals: ['Product', 'Partnerships', 'Press'],
    momentum: 97,
    lastUpdated: '2024-12-19',
    sourceHints: ['Public reporting'],
  },
  {
    id: 'chime',
    name: 'Chime',
    sector: 'Fintech',
    thesis: 'Neobank with 14M+ accounts. No-fee banking, early direct deposit, credit building.',
    whyTrending: 'Profitable. Revenue >$2B. IPO filing expected Q1 2025. Expanding lending products.',
    signals: ['Product', 'Press'],
    momentum: 88,
    lastUpdated: '2024-12-17',
    sourceHints: ['Public reporting'],
  },
  {
    id: 'figma',
    name: 'Figma',
    sector: 'DevTools',
    thesis: 'Collaborative design platform. Adobe acquisition blocked, now independent with renewed focus.',
    whyTrending: '$20B valuation maintained. AI design features launching. Enterprise growth accelerating.',
    signals: ['Product', 'Regulation', 'Press'],
    momentum: 85,
    lastUpdated: '2024-12-16',
    sourceHints: ['The Verge', 'TechCrunch'],
  },
  {
    id: 'scale-ai',
    name: 'Scale AI',
    sector: 'AI',
    thesis: 'Data labeling and AI training infrastructure. Powers models at OpenAI, Meta, Microsoft.',
    whyTrending: '$14B valuation. Government contracts expanding. Generative AI evaluation platform launched.',
    signals: ['Funding', 'Partnerships', 'Product'],
    momentum: 90,
    lastUpdated: '2024-12-14',
    sourceHints: ['Public reporting'],
  },
  {
    id: 'canva',
    name: 'Canva',
    sector: 'Consumer',
    thesis: 'Design platform for non-designers. 170M+ users. AI-powered design tools.',
    whyTrending: '$26B valuation. Magic Studio AI features viral. Enterprise tier growing 3x YoY.',
    signals: ['Product', 'Press'],
    momentum: 87,
    lastUpdated: '2024-12-13',
    sourceHints: ['Public reporting'],
  },
  {
    id: 'notion',
    name: 'Notion',
    sector: 'Enterprise',
    thesis: 'All-in-one workspace. Docs, wikis, projects, databases. Replacing multiple SaaS tools.',
    whyTrending: '$10B valuation. Notion AI launched. 100M+ users. Enterprise adoption accelerating.',
    signals: ['Product', 'Hiring', 'Press'],
    momentum: 84,
    lastUpdated: '2024-12-12',
    sourceHints: ['Public reporting'],
  },
  {
    id: 'rippling',
    name: 'Rippling',
    sector: 'Enterprise',
    thesis: 'Unified HR, IT, and finance platform. One system for employee lifecycle management.',
    whyTrending: '$13.5B valuation. ARR >$500M. Acquiring competitors. International expansion.',
    signals: ['Funding', 'Product', 'Partnerships'],
    momentum: 89,
    lastUpdated: '2024-12-11',
    sourceHints: ['Public reporting'],
  },
  {
    id: 'anduril',
    name: 'Anduril',
    sector: 'Enterprise',
    thesis: 'Defense tech. AI-powered autonomous systems for military and border security.',
    whyTrending: '$14B valuation. $1.5B Series F. Major DoD contracts. Lattice OS scaling.',
    signals: ['Funding', 'Partnerships', 'Product'],
    momentum: 91,
    lastUpdated: '2024-12-10',
    sourceHints: ['Public reporting'],
  },
  {
    id: 'revolut',
    name: 'Revolut',
    sector: 'Fintech',
    thesis: 'Digital banking super-app. 40M+ customers. Expanding into lending, crypto, investing.',
    whyTrending: '$33B valuation. UK banking license secured. US expansion accelerating. IPO rumors.',
    signals: ['Regulation', 'Product', 'Press'],
    momentum: 93,
    lastUpdated: '2024-12-09',
    sourceHints: ['Financial Times', 'Reuters'],
  },
  {
    id: 'mistral',
    name: 'Mistral AI',
    sector: 'AI',
    thesis: 'European AI champion. Open-source foundation models. Enterprise-focused.',
    whyTrending: '$6B valuation. Mixtral 8x7B outperforms GPT-3.5. Microsoft partnership. EU AI Act compliance.',
    signals: ['Funding', 'Product', 'Partnerships', 'Regulation'],
    momentum: 86,
    lastUpdated: '2024-12-08',
    sourceHints: ['Public reporting'],
  },
  {
    id: 'klarna',
    name: 'Klarna',
    sector: 'Fintech',
    thesis: 'Buy now, pay later leader. 150M+ users. Expanding into banking, shopping, AI.',
    whyTrending: '$6.7B valuation (down from $46B). Profitable. IPO expected 2025. AI customer service launched.',
    signals: ['Product', 'Press'],
    momentum: 82,
    lastUpdated: '2024-12-07',
    sourceHints: ['Public reporting'],
  },
  {
    id: 'cursor',
    name: 'Cursor',
    sector: 'DevTools',
    thesis: 'AI-first code editor. Built on VSCode. Autocomplete, chat, and edit powered by Claude/GPT-4.',
    whyTrending: 'Viral growth among developers. $400M valuation. Anysphere team. Competing with GitHub Copilot.',
    signals: ['Product', 'Hiring', 'Press'],
    momentum: 94,
    lastUpdated: '2024-12-24',
    sourceHints: ['Twitter', 'HackerNews'],
  },
  {
    id: 'perplexity',
    name: 'Perplexity',
    sector: 'AI',
    thesis: 'AI-powered search engine. Conversational answers with citations. Challenging Google.',
    whyTrending: '$3B valuation. 100M+ queries/month. Enterprise tier launched. Partnerships with publishers.',
    signals: ['Funding', 'Product', 'Partnerships', 'Competition'],
    momentum: 88,
    lastUpdated: '2024-12-23',
    sourceHints: ['Public reporting'],
  },
  {
    id: 'tempus',
    name: 'Tempus',
    sector: 'Healthcare',
    thesis: 'AI-driven precision medicine. Genomic sequencing, clinical data, and ML for cancer treatment.',
    whyTrending: 'Filed for IPO. $8B+ valuation. Partnerships with Mayo Clinic, Northwestern. Revenue >$500M.',
    signals: ['Product', 'Partnerships', 'Press'],
    momentum: 81,
    lastUpdated: '2024-12-06',
    sourceHints: ['Public reporting'],
  },
  {
    id: 'brex',
    name: 'Brex',
    sector: 'Fintech',
    thesis: 'Corporate cards and spend management for startups and enterprises.',
    whyTrending: '$12.3B valuation. Pivot to enterprise paying off. Empower acquisition. Revenue growing 50%+ YoY.',
    signals: ['Product', 'Partnerships'],
    momentum: 80,
    lastUpdated: '2024-12-05',
    sourceHints: ['Public reporting'],
  },
  {
    id: 'wiz',
    name: 'Wiz',
    sector: 'Enterprise',
    thesis: 'Cloud security platform. Unified CNAPP for AWS, Azure, GCP. Fastest SaaS to $100M ARR.',
    whyTrending: '$12B valuation. ARR >$500M. Rejected $23B Google acquisition. IPO expected 2025.',
    signals: ['Funding', 'Product', 'Press'],
    momentum: 96,
    lastUpdated: '2024-12-21',
    sourceHints: ['Public reporting'],
  },
  {
    id: 'airtable',
    name: 'Airtable',
    sector: 'Enterprise',
    thesis: 'No-code database platform. Spreadsheet UI with database power. Enterprise workflow automation.',
    whyTrending: '$11B valuation. AI features launched. Enterprise tier growing. IPO expected 2025.',
    signals: ['Product', 'Press'],
    momentum: 79,
    lastUpdated: '2024-12-04',
    sourceHints: ['Public reporting'],
  },
  {
    id: 'plaid',
    name: 'Plaid',
    sector: 'Fintech',
    thesis: 'Financial data connectivity. Powers Venmo, Robinhood, Coinbase. Open banking infrastructure.',
    whyTrending: '$13.4B valuation. Revenue >$1B. Expanding into payments, identity, crypto.',
    signals: ['Product', 'Partnerships'],
    momentum: 83,
    lastUpdated: '2024-12-03',
    sourceHints: ['Public reporting'],
  },
  {
    id: 'navan',
    name: 'Navan',
    sector: 'Enterprise',
    thesis: 'Corporate travel and expense management. All-in-one platform replacing Concur.',
    whyTrending: '$9.2B valuation. Profitable. Revenue >$1B. Enterprise wins accelerating.',
    signals: ['Product', 'Press'],
    momentum: 78,
    lastUpdated: '2024-12-02',
    sourceHints: ['Public reporting'],
  },
  {
    id: 'hugging-face',
    name: 'Hugging Face',
    sector: 'AI',
    thesis: 'Open-source AI platform. Model hub, datasets, inference. GitHub for AI.',
    whyTrending: '$4.5B valuation. 1M+ models hosted. Enterprise tier launched. AWS, Google partnerships.',
    signals: ['Funding', 'Product', 'Partnerships'],
    momentum: 85,
    lastUpdated: '2024-12-01',
    sourceHints: ['Public reporting'],
  },
  {
    id: 'devoted-health',
    name: 'Devoted Health',
    sector: 'Healthcare',
    thesis: 'Medicare Advantage insurer using tech to improve care and reduce costs.',
    whyTrending: '$12.6B valuation. 100K+ members. Expanding to new states. IPO expected 2025.',
    signals: ['Product', 'Regulation'],
    momentum: 77,
    lastUpdated: '2024-11-30',
    sourceHints: ['Public reporting'],
  },
  {
    id: 'faire',
    name: 'Faire',
    sector: 'Consumer',
    thesis: 'B2B marketplace connecting retailers with brands. Net-60 payment terms, free returns.',
    whyTrending: '$12.6B valuation. 700K+ retailers. Expanding internationally. Profitability path clear.',
    signals: ['Product', 'Partnerships'],
    momentum: 76,
    lastUpdated: '2024-11-29',
    sourceHints: ['Public reporting'],
  },
  {
    id: 'northvolt',
    name: 'Northvolt',
    sector: 'Climate',
    thesis: 'European battery manufacturer. Sustainable lithium-ion batteries for EVs and grid storage.',
    whyTrending: '$12B valuation. BMW, Volkswagen partnerships. Gigafactory operational. IPO expected 2025.',
    signals: ['Partnerships', 'Product', 'Regulation'],
    momentum: 80,
    lastUpdated: '2024-11-28',
    sourceHints: ['Reuters', 'Financial Times'],
  },
  {
    id: 'instacart',
    name: 'Instacart',
    sector: 'Consumer',
    thesis: 'Grocery delivery and advertising platform. 7.7M+ orders/week. Retail media network growing.',
    whyTrending: 'Public (CART). Post-IPO trading well. Advertising revenue scaling. Partnerships with retailers.',
    signals: ['Product', 'Partnerships', 'Press'],
    momentum: 75,
    lastUpdated: '2024-11-27',
    sourceHints: ['Public reporting'],
  },
  {
    id: 'ramp',
    name: 'Ramp',
    sector: 'Fintech',
    thesis: 'Corporate cards and spend management. AI-powered expense tracking and savings.',
    whyTrending: '$8.1B valuation. Fastest-growing SaaS. 25K+ customers. Competing with Brex, Navan.',
    signals: ['Funding', 'Product', 'Competition'],
    momentum: 87,
    lastUpdated: '2024-11-26',
    sourceHints: ['Public reporting'],
  },
  {
    id: 'flexport',
    name: 'Flexport',
    sector: 'Enterprise',
    thesis: 'Digital freight forwarding. Software-powered logistics for global trade.',
    whyTrending: '$8B valuation. Founder returned as CEO. Restructuring complete. Revenue >$3B.',
    signals: ['Product', 'Press'],
    momentum: 74,
    lastUpdated: '2024-11-25',
    sourceHints: ['Public reporting'],
  },
  {
    id: 'checkout',
    name: 'Checkout.com',
    sector: 'Fintech',
    thesis: 'Payment processing for global merchants. Competing with Stripe, Adyen.',
    whyTrending: '$40B valuation. Processing $500B+ annually. Expanding in APAC. IPO expected 2025.',
    signals: ['Product', 'Partnerships'],
    momentum: 84,
    lastUpdated: '2024-11-24',
    sourceHints: ['Public reporting'],
  },
  {
    id: 'samsara',
    name: 'Samsara',
    sector: 'Enterprise',
    thesis: 'IoT platform for physical operations. Fleet management, industrial automation, site visibility.',
    whyTrending: 'Public (IOT). $10B+ market cap. ARR >$1B. AI-powered safety features launching.',
    signals: ['Product', 'Press'],
    momentum: 73,
    lastUpdated: '2024-11-23',
    sourceHints: ['Public reporting'],
  },
  {
    id: 'gitlab',
    name: 'GitLab',
    sector: 'DevTools',
    thesis: 'DevSecOps platform. All-in-one CI/CD, security, and collaboration.',
    whyTrending: 'Public (GTLB). $8B+ market cap. AI-powered code suggestions. Enterprise growth strong.',
    signals: ['Product', 'Press'],
    momentum: 72,
    lastUpdated: '2024-11-22',
    sourceHints: ['Public reporting'],
  },
  {
    id: 'gusto',
    name: 'Gusto',
    sector: 'Enterprise',
    thesis: 'Payroll, benefits, and HR for SMBs. 300K+ customers. Embedded payroll for platforms.',
    whyTrending: '$10B valuation. Revenue >$500M. Profitable. IPO expected 2025.',
    signals: ['Product', 'Press'],
    momentum: 78,
    lastUpdated: '2024-11-21',
    sourceHints: ['Public reporting'],
  },
  {
    id: 'servicetitan',
    name: 'ServiceTitan',
    sector: 'Enterprise',
    thesis: 'Software for home services businesses. CRM, dispatch, payments, marketing.',
    whyTrending: '$18B valuation. Revenue >$800M. IPO filed. 100K+ contractors using platform.',
    signals: ['Product', 'Press'],
    momentum: 82,
    lastUpdated: '2024-11-20',
    sourceHints: ['Bloomberg', 'TechCrunch'],
  },
  {
    id: 'discord',
    name: 'Discord',
    sector: 'Consumer',
    thesis: 'Voice, video, and text communication for communities. 200M+ monthly users.',
    whyTrending: '$15B valuation. Monetization improving. Expanding beyond gaming. IPO expected 2025.',
    signals: ['Product', 'Press'],
    momentum: 81,
    lastUpdated: '2024-11-19',
    sourceHints: ['The Verge', 'TechCrunch'],
  },
  {
    id: 'reddit',
    name: 'Reddit',
    sector: 'Consumer',
    thesis: 'Social news aggregation and discussion. 500M+ monthly users. Advertising and premium subs.',
    whyTrending: 'Public (RDDT). $10B+ market cap. Post-IPO trading well. AI data licensing deals.',
    signals: ['Product', 'Partnerships', 'Press'],
    momentum: 79,
    lastUpdated: '2024-11-18',
    sourceHints: ['Public reporting'],
  },
  {
    id: 'rubrik',
    name: 'Rubrik',
    sector: 'Enterprise',
    thesis: 'Cloud data management and cyber recovery. Ransomware protection and backup.',
    whyTrending: '$6.4B valuation. IPO filed. ARR >$700M. Microsoft partnership. Cybersecurity focus.',
    signals: ['Product', 'Partnerships', 'Press'],
    momentum: 80,
    lastUpdated: '2024-11-17',
    sourceHints: ['Public reporting'],
  },
  {
    id: 'tanium',
    name: 'Tanium',
    sector: 'Enterprise',
    thesis: 'Endpoint management and security. Real-time visibility across enterprise IT.',
    whyTrending: '$9B valuation. Revenue >$500M. Government and Fortune 500 customers. IPO expected 2025.',
    signals: ['Product', 'Partnerships'],
    momentum: 77,
    lastUpdated: '2024-11-16',
    sourceHints: ['Public reporting'],
  },
  {
    id: 'snyk',
    name: 'Snyk',
    sector: 'DevTools',
    thesis: 'Developer security platform. Find and fix vulnerabilities in code, dependencies, containers.',
    whyTrending: '$7.4B valuation. ARR >$300M. AI-powered security fixes. Enterprise adoption growing.',
    signals: ['Funding', 'Product'],
    momentum: 76,
    lastUpdated: '2024-11-15',
    sourceHints: ['Public reporting'],
  },
];

export const IPO_CANDIDATES: IPOCandidate[] = [
  {
    id: 'stripe-ipo',
    name: 'Stripe',
    sector: 'Fintech',
    rumoredTimeframe: 'H2 2025',
    lastFundingRound: 'Series I, $6.5B at $50B valuation (2023)',
    publicPeers: ['Adyen', 'PayPal', 'Block (Square)'],
    riskNotes: 'Valuation down from $95B peak. Payment processing margins compressing. Macro sensitivity high.',
    momentum: 95,
    lastUpdated: '2024-12-18',
  },
  {
    id: 'databricks-ipo',
    name: 'Databricks',
    sector: 'Enterprise',
    rumoredTimeframe: 'Q2 2025',
    lastFundingRound: 'Series I, $500M at $43B valuation (2023)',
    publicPeers: ['Snowflake', 'MongoDB', 'Elastic'],
    riskNotes: 'High valuation multiple. Competition from Snowflake, AWS. Profitability timeline unclear.',
    momentum: 92,
    lastUpdated: '2024-12-15',
  },
  {
    id: 'chime-ipo',
    name: 'Chime',
    sector: 'Fintech',
    rumoredTimeframe: 'Q1 2025',
    lastFundingRound: 'Series G, $750M at $25B valuation (2021)',
    publicPeers: ['SoFi', 'Nu Holdings', 'Ally Financial'],
    riskNotes: 'Neobank profitability scrutiny. Regulatory risk. Interest rate sensitivity.',
    momentum: 88,
    lastUpdated: '2024-12-17',
  },
  {
    id: 'revolut-ipo',
    name: 'Revolut',
    sector: 'Fintech',
    rumoredTimeframe: 'H2 2025',
    lastFundingRound: 'Series E, $800M at $33B valuation (2021)',
    publicPeers: ['Wise', 'Nu Holdings', 'Monzo (private)'],
    riskNotes: 'UK/EU regulatory complexity. US expansion challenges. Profitability in select markets only.',
    momentum: 93,
    lastUpdated: '2024-12-09',
  },
  {
    id: 'klarna-ipo',
    name: 'Klarna',
    sector: 'Fintech',
    rumoredTimeframe: 'Q3 2025',
    lastFundingRound: 'Series H, $800M at $6.7B valuation (2022)',
    publicPeers: ['Affirm', 'Block', 'PayPal'],
    riskNotes: 'Valuation down 85% from peak. BNPL regulatory scrutiny. Credit risk in downturn.',
    momentum: 82,
    lastUpdated: '2024-12-07',
  },
  {
    id: 'wiz-ipo',
    name: 'Wiz',
    sector: 'Enterprise',
    rumoredTimeframe: 'Q2 2025',
    lastFundingRound: 'Series E, $1B at $12B valuation (2024)',
    publicPeers: ['CrowdStrike', 'Palo Alto Networks', 'Zscaler'],
    riskNotes: 'High growth expectations. Competition from incumbents. Cloud security market consolidation.',
    momentum: 96,
    lastUpdated: '2024-12-21',
  },
  {
    id: 'airtable-ipo',
    name: 'Airtable',
    sector: 'Enterprise',
    rumoredTimeframe: 'H2 2025',
    lastFundingRound: 'Series F, $735M at $11B valuation (2021)',
    publicPeers: ['Monday.com', 'Smartsheet', 'Asana'],
    riskNotes: 'Valuation compression in SaaS. Competition from Notion, Microsoft. Growth slowing.',
    momentum: 79,
    lastUpdated: '2024-12-04',
  },
  {
    id: 'devoted-health-ipo',
    name: 'Devoted Health',
    sector: 'Healthcare',
    rumoredTimeframe: 'Q3 2025',
    lastFundingRound: 'Series E, $1.15B at $12.6B valuation (2021)',
    publicPeers: ['Oscar Health', 'Clover Health', 'Humana'],
    riskNotes: 'Medicare Advantage regulatory risk. Medical loss ratio volatility. Capital intensive.',
    momentum: 77,
    lastUpdated: '2024-11-30',
  },
  {
    id: 'northvolt-ipo',
    name: 'Northvolt',
    sector: 'Climate',
    rumoredTimeframe: 'H2 2025',
    lastFundingRound: 'Series E, $1.2B at $12B valuation (2023)',
    publicPeers: ['QuantumScape', 'Solid Power', 'Panasonic'],
    riskNotes: 'Capital intensive. EV demand uncertainty. Chinese competition. Production ramp risk.',
    momentum: 80,
    lastUpdated: '2024-11-28',
  },
  {
    id: 'checkout-ipo',
    name: 'Checkout.com',
    sector: 'Fintech',
    rumoredTimeframe: 'Q4 2025',
    lastFundingRound: 'Series D, $1B at $40B valuation (2022)',
    publicPeers: ['Adyen', 'Stripe (private)', 'PayPal'],
    riskNotes: 'High valuation. Stripe/Adyen competition. Payment processing margin compression.',
    momentum: 84,
    lastUpdated: '2024-11-24',
  },
  {
    id: 'gusto-ipo',
    name: 'Gusto',
    sector: 'Enterprise',
    rumoredTimeframe: 'H1 2025',
    lastFundingRound: 'Series F, $175M at $10B valuation (2021)',
    publicPeers: ['Paycom', 'Paylocity', 'ADP'],
    riskNotes: 'SMB market cyclical. Competition from incumbents. Growth rate moderating.',
    momentum: 78,
    lastUpdated: '2024-11-21',
  },
  {
    id: 'servicetitan-ipo',
    name: 'ServiceTitan',
    sector: 'Enterprise',
    rumoredTimeframe: 'Q1 2025',
    lastFundingRound: 'Series F, $500M at $18B valuation (2022)',
    publicPeers: ['Jobber (private)', 'Housecall Pro (private)', 'ServiceMax'],
    riskNotes: 'Niche vertical market. High valuation. IPO filed but timing uncertain.',
    momentum: 82,
    lastUpdated: '2024-11-20',
  },
  {
    id: 'discord-ipo',
    name: 'Discord',
    sector: 'Consumer',
    rumoredTimeframe: 'H2 2025',
    lastFundingRound: 'Series H, $500M at $15B valuation (2021)',
    publicPeers: ['Roblox', 'Unity', 'Snap'],
    riskNotes: 'Monetization challenges. User growth slowing. Competition from gaming platforms.',
    momentum: 81,
    lastUpdated: '2024-11-19',
  },
  {
    id: 'rubrik-ipo',
    name: 'Rubrik',
    sector: 'Enterprise',
    rumoredTimeframe: 'Q2 2025',
    lastFundingRound: 'Series F, $752M at $6.4B valuation (2022)',
    publicPeers: ['Veeam (private)', 'Commvault', 'Cohesity (private)'],
    riskNotes: 'IPO filed. Backup market commoditizing. Cloud transition ongoing. Profitability unclear.',
    momentum: 80,
    lastUpdated: '2024-11-17',
  },
  {
    id: 'tanium-ipo',
    name: 'Tanium',
    sector: 'Enterprise',
    rumoredTimeframe: 'H2 2025',
    lastFundingRound: 'Series E, $175M at $9B valuation (2019)',
    publicPeers: ['CrowdStrike', 'SentinelOne', 'Qualys'],
    riskNotes: 'Long IPO delay. Government revenue concentration. Competition from endpoint security leaders.',
    momentum: 77,
    lastUpdated: '2024-11-16',
  },
  {
    id: 'snyk-ipo',
    name: 'Snyk',
    sector: 'DevTools',
    rumoredTimeframe: 'Q4 2025',
    lastFundingRound: 'Series G, $196M at $7.4B valuation (2022)',
    publicPeers: ['GitLab', 'JFrog', 'Sonatype (private)'],
    riskNotes: 'Developer security market crowded. GitHub competition. Profitability timeline unclear.',
    momentum: 76,
    lastUpdated: '2024-11-15',
  },
  {
    id: 'tempus-ipo',
    name: 'Tempus',
    sector: 'Healthcare',
    rumoredTimeframe: 'Q2 2025',
    lastFundingRound: 'Series G, $275M at $8.1B valuation (2022)',
    publicPeers: ['Guardant Health', 'Foundation Medicine', 'Exact Sciences'],
    riskNotes: 'IPO filed. Reimbursement risk. Precision medicine adoption pace. Regulatory complexity.',
    momentum: 81,
    lastUpdated: '2024-12-06',
  },
  {
    id: 'navan-ipo',
    name: 'Navan',
    sector: 'Enterprise',
    rumoredTimeframe: 'H2 2025',
    lastFundingRound: 'Series G, $154M at $9.2B valuation (2022)',
    publicPeers: ['Expensify', 'Concur (SAP)', 'Brex (private)'],
    riskNotes: 'Corporate travel cyclical. Competition from Brex, Ramp. Profitability achieved but growth slowing.',
    momentum: 78,
    lastUpdated: '2024-12-02',
  },
  {
    id: 'faire-ipo',
    name: 'Faire',
    sector: 'Consumer',
    rumoredTimeframe: 'Q3 2025',
    lastFundingRound: 'Series G, $416M at $12.6B valuation (2021)',
    publicPeers: ['Etsy', 'Shopify', 'Amazon Handmade'],
    riskNotes: 'Marketplace take rate pressure. Retailer churn risk. Macro sensitivity high.',
    momentum: 76,
    lastUpdated: '2024-11-29',
  },
  {
    id: 'flexport-ipo',
    name: 'Flexport',
    sector: 'Enterprise',
    rumoredTimeframe: 'H1 2026',
    lastFundingRound: 'Series E, $935M at $8B valuation (2022)',
    publicPeers: ['C.H. Robinson', 'Expeditors', 'XPO Logistics'],
    riskNotes: 'Freight market cyclical. Restructuring ongoing. Profitability timeline extended.',
    momentum: 74,
    lastUpdated: '2024-11-25',
  },
];

export const LAST_UPDATED = '2024-12-24';

