import {
  DEAL_CATEGORIES,
  type DealCurrency,
  type DealEntry,
  type WeeklyDealBrief,
} from '@/lib/deal-intelligence/types';

type DealSeed = Omit<DealEntry, 'id' | 'week' | 'featured' | 'date' | 'currency'> & {
  slug: string;
  date?: string;
  currency?: DealCurrency;
};

function createDeal(week: string, defaultDate: string, seed: DealSeed, featured: boolean): DealEntry {
  return {
    id: `${week}-${seed.slug}`,
    week,
    title: seed.title,
    date: seed.date ?? defaultDate,
    company: seed.company,
    counterparty: seed.counterparty,
    dealType: seed.dealType,
    category: seed.category,
    dealSize: seed.dealSize,
    currency: seed.currency ?? 'USD',
    sector: seed.sector,
    summary: seed.summary,
    whyItMatters: seed.whyItMatters,
    tags: seed.tags,
    featured,
    feedFrames: seed.feedFrames,
    sourceAttribution: seed.sourceAttribution,
  };
}

function createWeek(config: {
  week: string;
  title: string;
  startDate: string;
  endDate: string;
  marketSignal: WeeklyDealBrief['marketSignal'];
  analystTake: string;
  featuredSlug: string;
  deals: DealSeed[];
  feedSnapshots?: WeeklyDealBrief['feedSnapshots'];
  sourceAttribution?: WeeklyDealBrief['sourceAttribution'];
}): WeeklyDealBrief {
  const deals = config.deals.map((seed) =>
    createDeal(config.week, config.endDate, seed, seed.slug === config.featuredSlug)
  );

  return {
    id: config.week,
    week: config.week,
    title: config.title,
    date: config.endDate,
    startDate: config.startDate,
    endDate: config.endDate,
    marketSignal: config.marketSignal,
    analystTake: config.analystTake,
    deals,
    feedSnapshots: config.feedSnapshots,
    sourceAttribution: config.sourceAttribution,
  };
}

export const demoWeeklyDealBriefs: WeeklyDealBrief[] = [
  createWeek({
    week: '2026-W10',
    title: 'AI Infrastructure Scale Deals Lead a Selective Risk-On Tape',
    startDate: '2026-03-02',
    endDate: '2026-03-08',
    marketSignal: {
      tone: 'Balanced',
      headline: 'Large-cap buyers paid for infrastructure certainty while late-stage venture stayed price-disciplined.',
      detail:
        'Advisory desks reported stronger conviction on recurring-revenue infrastructure assets and tighter financing terms for subscale fintech names.',
    },
    analystTake:
      'The market is rewarding platforms with durable enterprise spend and clear unit economics. Deal velocity is healthy, but valuation support remains concentrated in high-quality assets.',
    featuredSlug: 'meridian-atlasswitch',
    deals: [
      {
        slug: 'meridian-atlasswitch',
        title: 'Meridian Compute to Acquire AtlasSwitch Data Fabric',
        company: 'AtlasSwitch Data Fabric',
        counterparty: 'Meridian Compute Partners',
        dealType: 'Strategic Acquisition',
        category: 'M&A',
        dealSize: 5200,
        sector: 'AI Infrastructure',
        summary: 'Meridian agreed to acquire AtlasSwitch to expand interconnect and orchestration capacity for enterprise AI clusters.',
        whyItMatters: 'Control of AI network fabric is becoming a strategic bottleneck, supporting premium strategic multiples.',
        tags: ['AI Infrastructure', 'Data Centers', 'Strategic M&A'],
        feedFrames: [
          {
            feed: 'IB',
            summary: 'A $5.2B strategic takeout signals buyers will still pay for scarce AI infrastructure platforms with enterprise contracts.',
            whyItMatters: 'Advisory and financing demand should stay concentrated in infrastructure assets with visible revenue durability.',
            tags: ['Strategic M&A', 'AI Infrastructure', 'Large Cap'],
            featured: true,
          },
          {
            feed: 'VC',
            summary: 'The deal resets late-stage valuation benchmarks for compute-adjacent venture portfolios.',
            whyItMatters: 'Venture-backed infrastructure names may see stronger crossover demand if monetization and utilization stay credible.',
            tags: ['Valuation Signal', 'Growth Capital', 'Infrastructure'],
          },
        ],
      },
      {
        slug: 'ledgerpilot-series-c',
        title: 'LedgerPilot Raises Series C for Merchant Treasury Automation',
        company: 'LedgerPilot',
        counterparty: 'Finch River Ventures',
        dealType: 'Series C',
        category: 'Venture Funding',
        dealSize: 185,
        sector: 'Fintech',
        summary: 'LedgerPilot raised growth capital to expand treasury and reconciliation automation for enterprise merchants.',
        whyItMatters: 'Investors continue to back fintech models with clear payback periods and embedded workflow stickiness.',
        tags: ['Fintech', 'Treasury Tech', 'Growth Equity'],
      },
      {
        slug: 'northbridge-take-private',
        title: 'Cedar Lane Takes Northbridge Treasury Systems Private',
        company: 'Northbridge Treasury Systems',
        counterparty: 'Cedar Lane Capital',
        dealType: 'Take-Private Buyout',
        category: 'Private Equity / Buyouts',
        dealSize: 1450,
        sector: 'Capital Markets Tech',
        summary: 'Cedar Lane signed a take-private of Northbridge with a private credit financing package.',
        whyItMatters: 'Sponsors remain active in mission-critical financial software with predictable renewal revenue.',
        tags: ['Buyout', 'Capital Markets Tech', 'Private Credit'],
      },
      {
        slug: 'prismpay-follow-on',
        title: 'PrismPay Networks Completes Follow-on Offering',
        company: 'PrismPay Networks',
        counterparty: 'Joint Bookrunner Syndicate',
        dealType: 'Follow-on Offering',
        category: 'ECM',
        dealSize: 640,
        sector: 'Payments',
        summary: 'PrismPay executed an overnight follow-on to fund cross-border acquiring expansion.',
        whyItMatters: 'ECM demand remains open for payment rails with defensible transaction growth.',
        tags: ['ECM', 'Payments', 'Follow-on'],
      },
      {
        slug: 'quantive-senior-notes',
        title: 'Quantive Market Data Prices Senior Unsecured Notes',
        company: 'Quantive Market Data',
        counterparty: 'Institutional Credit Investors',
        dealType: 'Senior Unsecured Notes',
        category: 'DCM',
        dealSize: 900,
        sector: 'Capital Markets Tech',
        summary: 'Quantive issued seven-year notes to refinance near-term maturities and fund platform upgrades.',
        whyItMatters: 'Credit markets still reward recurring data businesses with disciplined leverage profiles.',
        tags: ['DCM', 'Refinancing', 'Market Data'],
        feedFrames: [
          {
            feed: 'Capital Markets',
            summary: 'Quantive cleared a seven-year bond deal with constructive demand from long-duration credit accounts.',
            whyItMatters: 'Execution confirms funding access for issuers with recurring market-data cash flows despite selective spreads.',
            tags: ['DCM', 'Primary Markets', 'Funding Window'],
            featured: true,
          },
          {
            feed: 'Macro / Markets',
            summary: 'The note deal reinforces that higher-quality corporate issuers can still extend duration in a tighter rates regime.',
            whyItMatters: 'Credit reopening for durable issuers can reduce refinancing stress and stabilize broader risk sentiment.',
            tags: ['Credit Conditions', 'Rates Sensitivity', 'Refinancing'],
          },
        ],
      },
      {
        slug: 'clearsettle-aurorabank',
        title: 'ClearSettle and AuroraBank Launch Real-Time Settlement Alliance',
        company: 'ClearSettle',
        counterparty: 'AuroraBank',
        dealType: 'Commercial Partnership',
        category: 'Strategic Partnership',
        dealSize: null,
        sector: 'Payments',
        summary: 'The firms launched an API rail enabling near-instant merchant settlement for B2B marketplaces.',
        whyItMatters: 'Partnerships are accelerating distribution without requiring balance-sheet-heavy M&A.',
        tags: ['Strategic Partnership', 'Payments Rails', 'Banking APIs'],
      },
      {
        slug: 'ironroute-debt-exchange',
        title: 'IronRoute Merchant Acquiring Completes Debt Exchange',
        company: 'IronRoute Merchant Acquiring',
        counterparty: 'Ad Hoc Lender Group',
        dealType: 'Out-of-Court Debt Exchange',
        category: 'Restructuring',
        dealSize: 520,
        sector: 'Payments',
        summary: 'IronRoute pushed maturities by two years through a par-plus exchange and tighter covenants.',
        whyItMatters: 'Liability management remains the preferred path for subscale processors facing margin compression.',
        tags: ['Restructuring', 'Liability Management', 'Payments'],
      },
      {
        slug: 'fieldorbit-series-b',
        title: 'FieldOrbit Maintenance Cloud Raises Series B',
        company: 'FieldOrbit Maintenance Cloud',
        counterparty: 'Pine Street Growth',
        dealType: 'Series B',
        category: 'Venture Funding',
        dealSize: 95,
        sector: 'Vertical SaaS',
        summary: 'FieldOrbit raised expansion capital to scale industrial field-service workflows across utilities and logistics.',
        whyItMatters: 'Vertical SaaS continues to attract capital when retention and expansion metrics are visible.',
        tags: ['Vertical SaaS', 'Industrial Tech', 'Series B'],
      },
    ],
  }),
  createWeek({
    week: '2026-W09',
    title: 'Capital Markets Tech Reopens the IPO Window as Sponsors Stay Active',
    startDate: '2026-02-23',
    endDate: '2026-03-01',
    marketSignal: {
      tone: 'Balanced',
      headline: 'ECM quality improved while private-market pricing remained selective.',
      detail:
        'Book quality strengthened for infrastructure and market-utility issuers, while sponsors focused on operationally defensible software platforms.',
    },
    analystTake:
      'New issue demand exists, but investors still require clear earnings bridges. In private markets, buyers continue to prioritize mission-critical software with predictable renewal bases.',
    featuredSlug: 'bookforge-ipo',
    deals: [
      {
        slug: 'bookforge-ipo',
        title: 'BookForge Market Systems Prices Upsized IPO',
        company: 'BookForge Market Systems',
        counterparty: 'Lead-Left Syndicate',
        dealType: 'IPO',
        category: 'ECM',
        dealSize: 780,
        sector: 'Capital Markets Tech',
        summary: 'BookForge priced above midpoint after demand from long-only financials and tech funds.',
        whyItMatters: 'A successful cap-markets tech IPO improves confidence for the next software issuance cohort.',
        tags: ['IPO', 'Capital Markets Tech', 'ECM'],
      },
      {
        slug: 'helion-tokenspring',
        title: 'Helion Payments Acquires TokenSpring Risk Engine',
        company: 'TokenSpring Risk Engine',
        counterparty: 'Helion Payments',
        dealType: 'Strategic Acquisition',
        category: 'M&A',
        dealSize: 2100,
        sector: 'Payments',
        summary: 'Helion acquired TokenSpring to internalize fraud orchestration and merchant risk scoring.',
        whyItMatters: 'Payments platforms are consolidating risk tooling to protect take-rates and underwriting quality.',
        tags: ['M&A', 'Payments', 'Risk Infrastructure'],
      },
      {
        slug: 'modelrack-series-d',
        title: 'ModelRack Infra Raises Late-Stage Growth Round',
        company: 'ModelRack Infra',
        counterparty: 'Crosswind Capital',
        dealType: 'Series D',
        category: 'Venture Funding',
        dealSize: 320,
        sector: 'AI Infrastructure',
        summary: 'ModelRack raised growth capital to expand inference optimization across enterprise GPU fleets.',
        whyItMatters: 'Investors are funding AI infrastructure where efficiency gains directly lower compute cost per workload.',
        tags: ['AI Infrastructure', 'Series D', 'Enterprise AI'],
      },
      {
        slug: 'clinicflow-buyout',
        title: 'Summit Harbor Acquires ClinicFlow ERP Platform',
        company: 'ClinicFlow ERP',
        counterparty: 'Summit Harbor Partners',
        dealType: 'Control Buyout',
        category: 'Private Equity / Buyouts',
        dealSize: 980,
        sector: 'Vertical SaaS',
        summary: 'Summit Harbor acquired a majority stake in ClinicFlow to build a healthcare software platform.',
        whyItMatters: 'Healthcare vertical SaaS remains attractive to sponsors due to sticky workflows and recurring contracts.',
        tags: ['Private Equity', 'Vertical SaaS', 'Healthcare IT'],
      },
      {
        slug: 'vertex-term-loan-b',
        title: 'Vertex Lending Hub Raises Term Loan B',
        company: 'Vertex Lending Hub',
        counterparty: 'Institutional Loan Investors',
        dealType: 'Term Loan B',
        category: 'DCM',
        dealSize: 1100,
        sector: 'Fintech',
        summary: 'Vertex raised a TLB to refinance floating debt and add liquidity for product expansion.',
        whyItMatters: 'Loan markets are open for fintech issuers that can show improving cash generation.',
        tags: ['DCM', 'TLB', 'Fintech'],
      },
      {
        slug: 'coreledger-stratax',
        title: 'CoreLedger and StrataX Build Multi-Asset Connectivity Alliance',
        company: 'CoreLedger',
        counterparty: 'StrataX Exchange Services',
        dealType: 'Technology Partnership',
        category: 'Strategic Partnership',
        dealSize: null,
        sector: 'Capital Markets Tech',
        summary: 'The partnership integrates order routing and risk checks across listed and OTC venues.',
        whyItMatters: 'Connectivity alliances can capture enterprise spend faster than full-stack platform builds.',
        tags: ['Strategic Partnership', 'Market Structure', 'Trading Infrastructure'],
      },
      {
        slug: 'bluearc-covenant-reset',
        title: 'BlueArc Embedded Finance Executes Covenant Reset',
        company: 'BlueArc Embedded Finance',
        counterparty: 'First-Lien Steering Committee',
        dealType: 'Covenant Reset',
        category: 'Restructuring',
        dealSize: 430,
        sector: 'Fintech',
        summary: 'BlueArc negotiated covenant relief and delayed amortization to preserve liquidity.',
        whyItMatters: 'Smaller embedded-finance platforms still face funding pressure in a tighter credit backdrop.',
        tags: ['Restructuring', 'Fintech', 'Credit Stress'],
      },
      {
        slug: 'northtrail-revpilot',
        title: 'Northtrail Software Buys RevPilot CPQ Suite',
        company: 'RevPilot CPQ',
        counterparty: 'Northtrail Software',
        dealType: 'Bolt-on Acquisition',
        category: 'M&A',
        dealSize: 760,
        sector: 'Enterprise Software',
        summary: 'Northtrail acquired RevPilot to expand enterprise quote-to-cash workflow coverage.',
        whyItMatters: 'Mid-cap software buyers are using bolt-ons to improve platform attach rates and ARPU.',
        tags: ['Enterprise Software', 'Bolt-on M&A', 'Revenue Operations'],
      },
    ],
  }),
  createWeek({
    week: '2026-W08',
    title: 'Credit Markets Favor Infrastructure Duration While Early-Stage Rounds Normalize',
    startDate: '2026-02-16',
    endDate: '2026-02-22',
    marketSignal: {
      tone: 'Risk-On',
      headline: 'Duration demand supported large DCM execution in AI and infrastructure-adjacent issuers.',
      detail:
        'Early-stage rounds cleared at disciplined terms, while established issuers used debt markets to term out funding.',
    },
    analystTake:
      'Capital is available across the stack, but terms diverge sharply by quality. Investors continue to pay for infrastructure scarcity and measured growth efficiency.',
    featuredSlug: 'nimbus-cloud-notes',
    deals: [
      {
        slug: 'nimbus-cloud-notes',
        title: 'Nimbus Cloud Backbone Prices High-Yield Notes',
        company: 'Nimbus Cloud Backbone',
        counterparty: 'High-Yield Accounts',
        dealType: 'Senior Secured Notes',
        category: 'DCM',
        dealSize: 1750,
        sector: 'AI Infrastructure',
        summary: 'Nimbus issued secured notes to finance power and cooling upgrades across inference campuses.',
        whyItMatters: 'Debt investors are underwriting AI infrastructure where capacity is contracted and utilization is high.',
        tags: ['DCM', 'AI Infrastructure', 'Secured Notes'],
      },
      {
        slug: 'cobaltpay-remitpath',
        title: 'CobaltPay Acquires RemitPath FX Engine',
        company: 'RemitPath FX Engine',
        counterparty: 'CobaltPay',
        dealType: 'Strategic Acquisition',
        category: 'M&A',
        dealSize: 1650,
        sector: 'Fintech',
        summary: 'CobaltPay acquired RemitPath to improve cross-border pricing and treasury netting capabilities.',
        whyItMatters: 'Payments consolidation is shifting toward FX margin protection and routing efficiency.',
        tags: ['M&A', 'Fintech', 'Cross-border Payments'],
      },
      {
        slug: 'signalfoundry-series-a',
        title: 'SignalFoundry Raises Series A for Trade Surveillance AI',
        company: 'SignalFoundry',
        counterparty: 'Bridgepoint Ventures',
        dealType: 'Series A',
        category: 'Venture Funding',
        dealSize: 68,
        sector: 'Capital Markets Tech',
        summary: 'SignalFoundry raised capital to expand LLM-assisted surveillance workflows for broker-dealers.',
        whyItMatters: 'Regulatory automation remains a durable VC theme within capital markets software.',
        tags: ['Series A', 'RegTech', 'Capital Markets Tech'],
      },
      {
        slug: 'opsgenius-buyout',
        title: 'Harbor Crest Acquires OpsGenius Vertical ERP',
        company: 'OpsGenius',
        counterparty: 'Harbor Crest Equity',
        dealType: 'Platform Buyout',
        category: 'Private Equity / Buyouts',
        dealSize: 870,
        sector: 'Vertical SaaS',
        summary: 'Harbor Crest established OpsGenius as a platform for field-service ERP roll-ups.',
        whyItMatters: 'PE firms continue to favor fragmented vertical software where consolidation can drive margin expansion.',
        tags: ['Private Equity', 'Vertical SaaS', 'Platform Strategy'],
      },
      {
        slug: 'arrowlane-secondary',
        title: 'Arrowlane Software Executes Secondary Block Trade',
        company: 'Arrowlane Software',
        counterparty: 'Secondary Bookrunner Syndicate',
        dealType: 'Secondary Offering',
        category: 'ECM',
        dealSize: 420,
        sector: 'Enterprise Software',
        summary: 'Existing holders sold an accelerated block to increase institutional float.',
        whyItMatters: 'Clean secondary execution signals sustained institutional appetite for quality software names.',
        tags: ['ECM', 'Secondary', 'Enterprise Software'],
      },
      {
        slug: 'quantabid-meridian',
        title: 'QuantaBid and Meridian Exchange Co-Develop AI Execution Suite',
        company: 'QuantaBid',
        counterparty: 'Meridian Exchange',
        dealType: 'Product Alliance',
        category: 'Strategic Partnership',
        dealSize: null,
        sector: 'Capital Markets Tech',
        summary: 'The two firms launched a shared roadmap for AI-enhanced execution analytics and routing.',
        whyItMatters: 'Partnership-led product expansion can shorten time-to-market for institutional trading tools.',
        tags: ['Strategic Partnership', 'Trading Tech', 'AI'],
      },
      {
        slug: 'metropos-recap',
        title: 'MetroPOS Completes Preferred Recapitalization',
        company: 'MetroPOS',
        counterparty: 'Existing Preferred Holders',
        dealType: 'Preferred-Led Recapitalization',
        category: 'Restructuring',
        dealSize: 390,
        sector: 'Payments',
        summary: 'MetroPOS restructured preferred terms and extended liquidity runway by 18 months.',
        whyItMatters: 'Subscale payment processors continue to restructure before pursuing formal court processes.',
        tags: ['Restructuring', 'Payments', 'Recapitalization'],
      },
      {
        slug: 'kernelport-seed-plus',
        title: 'KernelPort Closes Seed Extension for GPU Scheduling Layer',
        company: 'KernelPort',
        counterparty: 'Frontline Seed',
        dealType: 'Seed Extension',
        category: 'Venture Funding',
        dealSize: 52,
        sector: 'AI Infrastructure',
        summary: 'KernelPort raised extension capital to commercialize cluster-level scheduler optimization software.',
        whyItMatters: 'Early AI infra funding remains available for software that improves utilization economics.',
        tags: ['Seed', 'AI Infrastructure', 'Compute Efficiency'],
      },
    ],
  }),
  createWeek({
    week: '2026-W07',
    title: 'Buyout Activity Broadens While Debt and Equity Windows Stay Constructive',
    startDate: '2026-02-09',
    endDate: '2026-02-15',
    marketSignal: {
      tone: 'Balanced',
      headline: 'Sponsor activity expanded into software and workflow assets despite selective underwriting.',
      detail:
        'Equity and debt issuance remained open for issuers with clear deleveraging use of proceeds and predictable customer retention.',
    },
    analystTake:
      'Buyers are paying for workflow ownership, not narrative growth. The strongest execution stories tie capital raises directly to margin expansion or balance-sheet repair.',
    featuredSlug: 'granite-ledgercloud',
    deals: [
      {
        slug: 'granite-ledgercloud',
        title: 'Granite Peak Buys LedgerCloud Enterprise Suite',
        company: 'LedgerCloud Enterprise Suite',
        counterparty: 'Granite Peak Capital',
        dealType: 'Control Buyout',
        category: 'Private Equity / Buyouts',
        dealSize: 2300,
        sector: 'Enterprise Software',
        summary: 'Granite Peak acquired LedgerCloud with plans to add adjacent compliance and analytics modules.',
        whyItMatters: 'Large buyout capital is concentrating in enterprise platforms with low churn and upsell depth.',
        tags: ['Private Equity', 'Enterprise Software', 'Control Buyout'],
      },
      {
        slug: 'orbitdata-vectorml',
        title: 'Orbit Data Works Merges with VectorML Serving',
        company: 'VectorML Serving',
        counterparty: 'Orbit Data Works',
        dealType: 'Strategic Merger',
        category: 'M&A',
        dealSize: 2800,
        sector: 'AI Infrastructure',
        summary: 'The combination creates an end-to-end model deployment and observability platform.',
        whyItMatters: 'Horizontal AI tooling is consolidating as enterprise buyers prefer integrated platforms.',
        tags: ['M&A', 'AI Infrastructure', 'Enterprise Platform'],
      },
      {
        slug: 'payflux-series-b',
        title: 'Payflux Compliance API Raises Series B',
        company: 'Payflux Compliance API',
        counterparty: 'Arbor Growth Partners',
        dealType: 'Series B',
        category: 'Venture Funding',
        dealSize: 140,
        sector: 'Fintech',
        summary: 'Payflux raised capital to scale compliance APIs for issuer processors and embedded finance programs.',
        whyItMatters: 'Regulatory tooling remains one of the most bankable fintech subsegments.',
        tags: ['Fintech', 'Series B', 'Compliance Infrastructure'],
      },
      {
        slug: 'crescent-follow-on',
        title: 'Crescent Treasury Tech Completes Follow-on',
        company: 'Crescent Treasury Tech',
        counterparty: 'Global Bookrunner Group',
        dealType: 'Follow-on Offering',
        category: 'ECM',
        dealSize: 510,
        sector: 'Capital Markets Tech',
        summary: 'Crescent raised primary equity to accelerate treasury orchestration product expansion.',
        whyItMatters: 'The market is still funding profitable or near-profitable financial software issuers.',
        tags: ['ECM', 'Follow-on', 'Treasury Tech'],
      },
      {
        slug: 'relaycommerce-abs',
        title: 'RelayCommerce Issues Receivables-Backed Facility',
        company: 'RelayCommerce',
        counterparty: 'ABS Investor Syndicate',
        dealType: 'Asset-Backed Financing',
        category: 'DCM',
        dealSize: 760,
        sector: 'Payments',
        summary: 'RelayCommerce expanded warehouse capacity through a receivables-backed issuance.',
        whyItMatters: 'Structured credit remains a key funding lever for transaction-heavy fintech models.',
        tags: ['DCM', 'ABS', 'Payments'],
      },
      {
        slug: 'shifterp-harborpay',
        title: 'ShiftERP and HarborPay Expand Embedded AP Offering',
        company: 'ShiftERP',
        counterparty: 'HarborPay',
        dealType: 'Distribution Partnership',
        category: 'Strategic Partnership',
        dealSize: null,
        sector: 'Enterprise Software',
        summary: 'ShiftERP embedded HarborPay rails into its procurement suite for enterprise clients.',
        whyItMatters: 'Embedded payments partnerships can drive both software retention and payment monetization.',
        tags: ['Strategic Partnership', 'Embedded Payments', 'ERP'],
      },
      {
        slug: 'altis-invoice-exchange',
        title: 'Altis Invoice Finance Completes Exchange Offer',
        company: 'Altis Invoice Finance',
        counterparty: 'First-Lien Noteholders',
        dealType: 'Debt Exchange',
        category: 'Restructuring',
        dealSize: 610,
        sector: 'Fintech',
        summary: 'Altis exchanged short-dated notes for longer tenor instruments with enhanced collateral terms.',
        whyItMatters: 'Credit investors are extending runway where operating metrics remain salvageable.',
        tags: ['Restructuring', 'Fintech Credit', 'Debt Exchange'],
      },
      {
        slug: 'sitepilot-series-a',
        title: 'SitePilot Field Service AI Raises Series A',
        company: 'SitePilot Field Service AI',
        counterparty: 'Northline Ventures',
        dealType: 'Series A',
        category: 'Venture Funding',
        dealSize: 74,
        sector: 'Vertical SaaS',
        summary: 'SitePilot raised capital to automate dispatch and technician planning for industrial service firms.',
        whyItMatters: 'Vertical AI-enabled SaaS remains attractive when tied to measurable labor productivity gains.',
        tags: ['Vertical SaaS', 'Series A', 'Industrial Workflows'],
      },
    ],
  }),
  createWeek({
    week: '2026-W06',
    title: 'Strategic Buyers Return to Fintech Infrastructure as Issuance Activity Holds',
    startDate: '2026-02-02',
    endDate: '2026-02-08',
    marketSignal: {
      tone: 'Risk-On',
      headline: 'Strategic M&A in financial infrastructure accelerated with financing markets still open.',
      detail:
        'Advisors cited stronger board-level urgency around owning core rails and reducing third-party dependency.',
    },
    analystTake:
      'Execution is best for assets tied to core transaction workflows. Investors remain willing to fund growth, but only where revenue durability is visible.',
    featuredSlug: 'novafin-capitalnexus',
    deals: [
      {
        slug: 'novafin-capitalnexus',
        title: 'NovaFin to Acquire CapitalNexus OMS Platform',
        company: 'CapitalNexus OMS',
        counterparty: 'NovaFin Holdings',
        dealType: 'Strategic Acquisition',
        category: 'M&A',
        dealSize: 3400,
        sector: 'Capital Markets Tech',
        summary: 'NovaFin agreed to acquire CapitalNexus to unify order management, compliance, and post-trade workflows.',
        whyItMatters: 'Front-to-back platform integration is a major strategic priority for financial infrastructure incumbents.',
        tags: ['M&A', 'Capital Markets Tech', 'Workflow Consolidation'],
      },
      {
        slug: 'agentstack-series-c',
        title: 'AgentStack Workspace Raises Series C',
        company: 'AgentStack Workspace',
        counterparty: 'Harborline Growth',
        dealType: 'Series C',
        category: 'Venture Funding',
        dealSize: 210,
        sector: 'Enterprise Software',
        summary: 'AgentStack raised growth equity to expand AI-enabled workflow tooling for support and operations teams.',
        whyItMatters: 'Enterprise software funding remains robust for products with clear seat expansion and retention metrics.',
        tags: ['Enterprise Software', 'Series C', 'Workflow Automation'],
      },
      {
        slug: 'mediroute-buyout',
        title: 'Ridgeway Sponsors Buyout of MediRoute RCM Platform',
        company: 'MediRoute RCM',
        counterparty: 'Ridgeway Capital',
        dealType: 'Platform Buyout',
        category: 'Private Equity / Buyouts',
        dealSize: 1250,
        sector: 'Vertical SaaS',
        summary: 'Ridgeway acquired MediRoute to build a scaled healthcare revenue-cycle software platform.',
        whyItMatters: 'RCM software remains sponsor-friendly due to sticky contracts and fragmented market structure.',
        tags: ['Private Equity', 'Vertical SaaS', 'Healthcare RCM'],
      },
      {
        slug: 'zenith-dual-listing',
        title: 'Zenith Clearing Completes Dual-Market Follow-on',
        company: 'Zenith Clearing',
        counterparty: 'Joint Global Coordinators',
        dealType: 'Follow-on Offering',
        category: 'ECM',
        dealSize: 690,
        sector: 'Capital Markets Tech',
        summary: 'Zenith raised equity in a dual-market placement to support new collateral management modules.',
        whyItMatters: 'Cross-market ECM execution suggests deeper institutional demand for financial software names.',
        tags: ['ECM', 'Follow-on', 'Clearing Infrastructure'],
      },
      {
        slug: 'trustlayer-notes',
        title: 'TrustLayer Payments Issues Senior Secured Notes',
        company: 'TrustLayer Payments',
        counterparty: 'High-Yield Accounts',
        dealType: 'Senior Secured Notes',
        category: 'DCM',
        dealSize: 980,
        sector: 'Payments',
        summary: 'TrustLayer raised secured debt to refinance prior warehouse financing and reduce rate volatility.',
        whyItMatters: 'Payments issuers can still access credit when proceeds support liability optimization.',
        tags: ['DCM', 'Payments', 'Refinancing'],
      },
      {
        slug: 'framegrid-ioncompute',
        title: 'FrameGrid and IonCompute Sign Bare-Metal Capacity Pact',
        company: 'FrameGrid',
        counterparty: 'IonCompute',
        dealType: 'Capacity Partnership',
        category: 'Strategic Partnership',
        dealSize: null,
        sector: 'AI Infrastructure',
        summary: 'FrameGrid secured long-duration compute capacity via a multi-year bare-metal partnership.',
        whyItMatters: 'Capacity partnerships are becoming an alternative to expensive infrastructure acquisitions.',
        tags: ['Strategic Partnership', 'AI Infrastructure', 'Compute Capacity'],
      },
      {
        slug: 'deltaledger-prepack',
        title: 'DeltaLedger Files Pre-Pack Plan with Creditor Support',
        company: 'DeltaLedger',
        counterparty: 'Senior Creditor Committee',
        dealType: 'Pre-Packaged Restructuring',
        category: 'Restructuring',
        dealSize: 550,
        sector: 'Fintech',
        summary: 'DeltaLedger launched a pre-pack process after negotiating term sheets with senior lenders.',
        whyItMatters: 'Pre-pack processes can preserve enterprise value and shorten execution risk for creditors.',
        tags: ['Restructuring', 'Fintech', 'Pre-Pack'],
      },
      {
        slug: 'harborcard-swiftauth',
        title: 'HarborCard Acquires SwiftAuth Fraud Tooling',
        company: 'SwiftAuth',
        counterparty: 'HarborCard',
        dealType: 'Bolt-on Acquisition',
        category: 'M&A',
        dealSize: 890,
        sector: 'Payments',
        summary: 'HarborCard acquired SwiftAuth to improve real-time authorization and fraud decisioning.',
        whyItMatters: 'Fraud stack ownership is increasingly central to payment margin and approval-rate performance.',
        tags: ['M&A', 'Payments', 'Fraud Tech'],
      },
    ],
  }),
  createWeek({
    week: '2026-W05',
    title: 'Late-Stage Venture Rebounds While Issuers Use Public Markets Opportunistically',
    startDate: '2026-01-26',
    endDate: '2026-02-01',
    marketSignal: {
      tone: 'Balanced',
      headline: 'Large private rounds returned for AI platforms with clear enterprise demand signals.',
      detail:
        'ECM and DCM windows remained open, but investors favored proceeds tied to deleveraging and infrastructure efficiency.',
    },
    analystTake:
      'Investors are underwriting growth where cost curves are improving and sales cycles are shortening. Capital is available, but terms still punish weak execution narratives.',
    featuredSlug: 'tensordock-series-e',
    deals: [
      {
        slug: 'tensordock-series-e',
        title: 'TensorDock Infra Raises Series E',
        company: 'TensorDock Infra',
        counterparty: 'Northwood Growth',
        dealType: 'Series E',
        category: 'Venture Funding',
        dealSize: 540,
        sector: 'AI Infrastructure',
        summary: 'TensorDock raised late-stage capital to expand inference hosting and model optimization services.',
        whyItMatters: 'Mega rounds are still available for AI infra providers with visible enterprise contracts.',
        tags: ['Venture Funding', 'AI Infrastructure', 'Late Stage'],
      },
      {
        slug: 'primesettle-bondops',
        title: 'PrimeSettle Acquires BondOps Workflow Suite',
        company: 'BondOps Workflow',
        counterparty: 'PrimeSettle',
        dealType: 'Strategic Acquisition',
        category: 'M&A',
        dealSize: 1900,
        sector: 'Capital Markets Tech',
        summary: 'PrimeSettle acquired BondOps to deepen fixed-income automation and post-trade analytics.',
        whyItMatters: 'Fixed-income stack consolidation is accelerating as firms seek front-to-back efficiency.',
        tags: ['M&A', 'Capital Markets Tech', 'Fixed Income'],
      },
      {
        slug: 'fleetpulse-buyout',
        title: 'Oakline Partners Acquires FleetPulse TMS Platform',
        company: 'FleetPulse TMS',
        counterparty: 'Oakline Partners',
        dealType: 'Control Buyout',
        category: 'Private Equity / Buyouts',
        dealSize: 760,
        sector: 'Vertical SaaS',
        summary: 'Oakline acquired FleetPulse to build a transportation software platform strategy.',
        whyItMatters: 'Vertical SaaS buyouts continue to clear where implementation depth drives customer retention.',
        tags: ['Private Equity', 'Vertical SaaS', 'Transportation Tech'],
      },
      {
        slug: 'mercury-paytech-ipo',
        title: 'Mercury Paytech Prices IPO',
        company: 'Mercury Paytech',
        counterparty: 'Lead Bookrunner Syndicate',
        dealType: 'IPO',
        category: 'ECM',
        dealSize: 830,
        sector: 'Payments',
        summary: 'Mercury Paytech priced an IPO to fund network expansion and product development.',
        whyItMatters: 'A successful payments IPO broadens the addressable ECM window for growth fintech issuers.',
        tags: ['ECM', 'IPO', 'Payments'],
      },
      {
        slug: 'aster-sub-notes',
        title: 'Aster Finserv Issues Subordinated Notes',
        company: 'Aster Finserv',
        counterparty: 'Institutional Credit Accounts',
        dealType: 'Subordinated Notes',
        category: 'DCM',
        dealSize: 620,
        sector: 'Fintech',
        summary: 'Aster placed subordinated debt to support lending-book diversification and capital ratios.',
        whyItMatters: 'Investors remain open to fintech credit where portfolio quality and funding discipline are improving.',
        tags: ['DCM', 'Fintech', 'Subordinated Debt'],
      },
      {
        slug: 'rulestack-civicbank',
        title: 'RuleStack and CivicBank Build Compliance Integration Stack',
        company: 'RuleStack',
        counterparty: 'CivicBank',
        dealType: 'Go-to-Market Partnership',
        category: 'Strategic Partnership',
        dealSize: null,
        sector: 'Enterprise Software',
        summary: 'RuleStack integrated its controls engine into CivicBank’s commercial onboarding workflow.',
        whyItMatters: 'Bank distribution partnerships are a capital-light growth lever for enterprise regtech providers.',
        tags: ['Strategic Partnership', 'RegTech', 'Enterprise Software'],
      },
      {
        slug: 'beacon-liquidity-swap',
        title: 'Beacon Merchant Services Executes Liquidity Swap',
        company: 'Beacon Merchant Services',
        counterparty: 'Secured Lender Group',
        dealType: 'Liquidity Swap',
        category: 'Restructuring',
        dealSize: 470,
        sector: 'Payments',
        summary: 'Beacon exchanged near-term obligations for a longer-dated secured instrument.',
        whyItMatters: 'Restructuring activity remains elevated among payment firms with weaker volume mix.',
        tags: ['Restructuring', 'Payments', 'Liquidity'],
      },
      {
        slug: 'contractmint-series-b',
        title: 'ContractMint AI Raises Series B',
        company: 'ContractMint AI',
        counterparty: 'Stone Arch Ventures',
        dealType: 'Series B',
        category: 'Venture Funding',
        dealSize: 125,
        sector: 'Enterprise Software',
        summary: 'ContractMint raised capital to expand legal and procurement workflow automation for enterprises.',
        whyItMatters: 'AI-enabled workflow software still attracts capital where ROI is directly measurable.',
        tags: ['Venture Funding', 'Enterprise Software', 'Workflow AI'],
      },
    ],
  }),
  createWeek({
    week: '2026-W04',
    title: 'Distressed Activity Rises in Fintech as Infrastructure M&A Remains Firm',
    startDate: '2026-01-19',
    endDate: '2026-01-25',
    marketSignal: {
      tone: 'Risk-Off',
      headline: 'Credit stress appeared in smaller fintech names even as strategic infrastructure deals held up.',
      detail:
        'Sponsors were active in resilient vertical software while lenders pushed tighter protections in challenged payment models.',
    },
    analystTake:
      'The market is bifurcating between scaled operators and subscale platforms. High-quality infrastructure assets still command interest, while weaker credits are shifting into restructuring mode.',
    featuredSlug: 'horizon-out-of-court',
    deals: [
      {
        slug: 'horizon-out-of-court',
        title: 'Horizon Lending Platform Executes Out-of-Court Recapitalization',
        company: 'Horizon Lending Platform',
        counterparty: 'Senior Secured Lenders',
        dealType: 'Out-of-Court Recapitalization',
        category: 'Restructuring',
        dealSize: 1300,
        sector: 'Fintech',
        summary: 'Horizon completed a lender-led recap with partial debt-to-equity conversion and maturity extension.',
        whyItMatters: 'Large consensual restructurings can reset leverage without value-destructive court timelines.',
        tags: ['Restructuring', 'Fintech', 'Debt-to-Equity'],
      },
      {
        slug: 'cloudroute-infraoptic',
        title: 'CloudRoute Acquires InfraOptic Telemetry Platform',
        company: 'InfraOptic Telemetry',
        counterparty: 'CloudRoute Systems',
        dealType: 'Strategic Acquisition',
        category: 'M&A',
        dealSize: 2600,
        sector: 'AI Infrastructure',
        summary: 'CloudRoute acquired InfraOptic to improve observability and uptime controls for AI clusters.',
        whyItMatters: 'Reliability tooling is becoming a strategic differentiator in AI infrastructure procurement.',
        tags: ['M&A', 'AI Infrastructure', 'Observability'],
      },
      {
        slug: 'nimbletreasury-series-a',
        title: 'NimbleTreasury Raises Series A',
        company: 'NimbleTreasury',
        counterparty: 'Canyon Seed Partners',
        dealType: 'Series A',
        category: 'Venture Funding',
        dealSize: 58,
        sector: 'Fintech',
        summary: 'NimbleTreasury raised funding for SMB treasury and cash forecasting automation.',
        whyItMatters: 'Early-stage fintech remains active where product value ties directly to working-capital outcomes.',
        tags: ['Venture Funding', 'Fintech', 'Treasury'],
      },
      {
        slug: 'buildloop-buyout',
        title: 'Mariner Equity Acquires BuildLoop Construction ERP',
        company: 'BuildLoop Construction ERP',
        counterparty: 'Mariner Equity',
        dealType: 'Platform Buyout',
        category: 'Private Equity / Buyouts',
        dealSize: 920,
        sector: 'Vertical SaaS',
        summary: 'Mariner acquired BuildLoop as a platform for construction and field operations software.',
        whyItMatters: 'Vertical ERP assets continue to attract PE due to workflow lock-in and durable renewal behavior.',
        tags: ['Private Equity', 'Vertical SaaS', 'Construction Tech'],
      },
      {
        slug: 'dataquorum-follow-on',
        title: 'DataQuorum Analytics Completes Follow-on Raise',
        company: 'DataQuorum Analytics',
        counterparty: 'Joint Bookrunners',
        dealType: 'Follow-on Offering',
        category: 'ECM',
        dealSize: 460,
        sector: 'Enterprise Software',
        summary: 'DataQuorum raised equity to fund AI-assisted forecasting modules for enterprise clients.',
        whyItMatters: 'Investors continue to support profitable analytics platforms with clear upsell paths.',
        tags: ['ECM', 'Enterprise Software', 'Follow-on'],
      },
      {
        slug: 'pulsepay-abs',
        title: 'PulsePay Prices Receivables ABS Facility',
        company: 'PulsePay',
        counterparty: 'Structured Credit Investors',
        dealType: 'Asset-Backed Security',
        category: 'DCM',
        dealSize: 840,
        sector: 'Payments',
        summary: 'PulsePay expanded funding capacity through a receivables-backed issuance.',
        whyItMatters: 'ABS remains a critical funding channel for transaction-heavy payment businesses.',
        tags: ['DCM', 'ABS', 'Payments'],
      },
      {
        slug: 'marketwirex-orbitalai',
        title: 'MarketWireX and OrbitalAI Partner on Event Intelligence',
        company: 'MarketWireX',
        counterparty: 'OrbitalAI',
        dealType: 'Data Partnership',
        category: 'Strategic Partnership',
        dealSize: null,
        sector: 'Capital Markets Tech',
        summary: 'The partnership integrates macro event intelligence into sell-side and buy-side workflow terminals.',
        whyItMatters: 'Data partnerships can accelerate product depth without large acquisition premiums.',
        tags: ['Strategic Partnership', 'Market Data', 'AI'],
      },
      {
        slug: 'codeharbor-series-c',
        title: 'CodeHarbor Workflow Suite Raises Series C',
        company: 'CodeHarbor Workflow Suite',
        counterparty: 'Summit Lane Growth',
        dealType: 'Series C',
        category: 'Venture Funding',
        dealSize: 175,
        sector: 'Enterprise Software',
        summary: 'CodeHarbor raised growth equity to scale enterprise workflow orchestration across operations teams.',
        whyItMatters: 'Growth rounds remain available for enterprise software with efficient expansion economics.',
        tags: ['Venture Funding', 'Enterprise Software', 'Series C'],
      },
    ],
  }),
  createWeek({
    week: '2026-W03',
    title: 'Partnership-First Expansion Accelerates Across Trading and Payments Rails',
    startDate: '2026-01-12',
    endDate: '2026-01-18',
    marketSignal: {
      tone: 'Balanced',
      headline: 'Firms used partnerships to expand distribution while preserving capital flexibility.',
      detail:
        'M&A remained active in core fintech infrastructure, but alliance-led launches increased in capital markets and payments.',
    },
    analystTake:
      'The partnership model is now a mainstream growth path, especially where integration speed matters. Strategic buyers still pursue control deals when ownership of the core rail is critical.',
    featuredSlug: 'stratus-apexcompute',
    deals: [
      {
        slug: 'stratus-apexcompute',
        title: 'Stratus Exchange and ApexCompute Launch Co-Located AI Trading Cloud',
        company: 'Stratus Exchange',
        counterparty: 'ApexCompute',
        dealType: 'Strategic Infrastructure Partnership',
        category: 'Strategic Partnership',
        dealSize: null,
        sector: 'Capital Markets Tech',
        summary: 'Stratus and ApexCompute launched a low-latency AI compute environment adjacent to exchange infrastructure.',
        whyItMatters: 'Co-located partnerships can create defensible distribution and latency advantages without full M&A.',
        tags: ['Strategic Partnership', 'Capital Markets Tech', 'AI Infrastructure'],
      },
      {
        slug: 'finbeam-vaultkyc',
        title: 'Finbeam Acquires VaultKYC Verification Stack',
        company: 'VaultKYC',
        counterparty: 'Finbeam',
        dealType: 'Strategic Acquisition',
        category: 'M&A',
        dealSize: 1150,
        sector: 'Fintech',
        summary: 'Finbeam acquired VaultKYC to internalize onboarding and compliance workflows.',
        whyItMatters: 'Owning compliance rails can improve margin and reduce third-party operational risk.',
        tags: ['M&A', 'Fintech', 'KYC'],
      },
      {
        slug: 'doseflow-series-b',
        title: 'DoseFlow RCM AI Raises Series B',
        company: 'DoseFlow RCM AI',
        counterparty: 'Harbor Seed & Growth',
        dealType: 'Series B',
        category: 'Venture Funding',
        dealSize: 92,
        sector: 'Vertical SaaS',
        summary: 'DoseFlow raised capital to automate coding and denial management in healthcare revenue cycle workflows.',
        whyItMatters: 'Vertical SaaS AI companies with direct margin impact continue to raise efficiently.',
        tags: ['Venture Funding', 'Vertical SaaS', 'Healthcare AI'],
      },
      {
        slug: 'tradesuite-buyout',
        title: 'Northfield Partners Buys TradeSuite OMS',
        company: 'TradeSuite OMS',
        counterparty: 'Northfield Partners',
        dealType: 'Control Buyout',
        category: 'Private Equity / Buyouts',
        dealSize: 1500,
        sector: 'Capital Markets Tech',
        summary: 'Northfield acquired TradeSuite to build a multi-asset trading workflow platform.',
        whyItMatters: 'Sponsors continue to target market infrastructure software with sticky institutional users.',
        tags: ['Private Equity', 'Capital Markets Tech', 'Buyout'],
      },
      {
        slug: 'helioerp-secondary',
        title: 'HelioERP Completes Secondary Offering',
        company: 'HelioERP',
        counterparty: 'Secondary Bookrunner Syndicate',
        dealType: 'Secondary Offering',
        category: 'ECM',
        dealSize: 390,
        sector: 'Enterprise Software',
        summary: 'HelioERP completed a secondary block to increase free float and broaden ownership.',
        whyItMatters: 'Successful secondary placements improve liquidity and support future primary issuance optionality.',
        tags: ['ECM', 'Enterprise Software', 'Secondary'],
      },
      {
        slug: 'quantrail-notes',
        title: 'QuantRail Infrastructure Issues Benchmark Notes',
        company: 'QuantRail Infrastructure',
        counterparty: 'Investment-Grade Accounts',
        dealType: 'Benchmark Bond Issuance',
        category: 'DCM',
        dealSize: 1250,
        sector: 'AI Infrastructure',
        summary: 'QuantRail issued long-dated notes to fund compute campus expansion and refinance short maturities.',
        whyItMatters: 'Long-duration funding remains available for contracted infrastructure cash flows.',
        tags: ['DCM', 'AI Infrastructure', 'Investment Grade'],
      },
      {
        slug: 'omnicheckout-swap',
        title: 'OmniCheckout Executes Debt-for-Equity Swap',
        company: 'OmniCheckout',
        counterparty: 'Second-Lien Creditors',
        dealType: 'Debt-for-Equity Swap',
        category: 'Restructuring',
        dealSize: 510,
        sector: 'Payments',
        summary: 'OmniCheckout converted part of junior debt into equity to reduce interest burden.',
        whyItMatters: 'Payment firms with weaker growth profiles are prioritizing cap-table repair over fresh debt issuance.',
        tags: ['Restructuring', 'Payments', 'Debt-for-Equity'],
      },
      {
        slug: 'paynest-crossborderiq',
        title: 'PayNest Acquires CrossBorderIQ Compliance Layer',
        company: 'CrossBorderIQ',
        counterparty: 'PayNest',
        dealType: 'Bolt-on Acquisition',
        category: 'M&A',
        dealSize: 720,
        sector: 'Payments',
        summary: 'PayNest acquired CrossBorderIQ to streamline cross-border screening and routing logic.',
        whyItMatters: 'Cross-border compliance automation is becoming a prerequisite for scaling payment corridors.',
        tags: ['M&A', 'Payments', 'Cross-border'],
      },
    ],
  }),
  createWeek({
    week: '2026-W02',
    title: 'Public Equity Receptivity Improves as Fintech Infrastructure Consolidates',
    startDate: '2026-01-05',
    endDate: '2026-01-11',
    marketSignal: {
      tone: 'Risk-On',
      headline: 'Follow-on and primary equity demand improved for scaled fintech and software issuers.',
      detail:
        'Strategic acquirers were active in risk and surveillance tooling, while debt markets stayed open for creditworthy growth names.',
    },
    analystTake:
      'Investor appetite is broadening, but still rewards clarity on profitability and capital efficiency. Strategic consolidation remains strongest in infrastructure and risk management.',
    featuredSlug: 'vectorpay-follow-on',
    deals: [
      {
        slug: 'vectorpay-follow-on',
        title: 'VectorPay Holdings Executes Upsized Follow-on',
        company: 'VectorPay Holdings',
        counterparty: 'Lead Bookrunners',
        dealType: 'Follow-on Offering',
        category: 'ECM',
        dealSize: 980,
        sector: 'Payments',
        summary: 'VectorPay upsized its follow-on offering after strong institutional demand.',
        whyItMatters: 'Improved ECM depth for payments issuers can reopen funding pathways for scaled fintech platforms.',
        tags: ['ECM', 'Payments', 'Follow-on'],
      },
      {
        slug: 'aurora-risktide',
        title: 'Aurora Ledger to Acquire RiskTide Surveillance',
        company: 'RiskTide Surveillance',
        counterparty: 'Aurora Ledger',
        dealType: 'Strategic Acquisition',
        category: 'M&A',
        dealSize: 2400,
        sector: 'Capital Markets Tech',
        summary: 'Aurora Ledger agreed to acquire RiskTide to add trade surveillance and conduct monitoring capabilities.',
        whyItMatters: 'Surveillance stack ownership is increasingly strategic as compliance cost and complexity rise.',
        tags: ['M&A', 'Capital Markets Tech', 'RegTech'],
      },
      {
        slug: 'corepolicy-series-a',
        title: 'CorePolicy Underwriting AI Raises Series A',
        company: 'CorePolicy Underwriting AI',
        counterparty: 'Red Cedar Ventures',
        dealType: 'Series A',
        category: 'Venture Funding',
        dealSize: 63,
        sector: 'Fintech',
        summary: 'CorePolicy raised capital to automate underwriting workflows for specialty lenders.',
        whyItMatters: 'Lending automation remains fundable where models improve approval speed and loss outcomes.',
        tags: ['Venture Funding', 'Fintech', 'Underwriting AI'],
      },
      {
        slug: 'vetflow-buyout',
        title: 'Sterling Point Acquires VetFlow Practice OS',
        company: 'VetFlow Practice OS',
        counterparty: 'Sterling Point Capital',
        dealType: 'Sponsor Buyout',
        category: 'Private Equity / Buyouts',
        dealSize: 680,
        sector: 'Vertical SaaS',
        summary: 'Sterling Point acquired VetFlow to anchor a veterinary practice management roll-up.',
        whyItMatters: 'Specialized practice-management software continues to command sponsor interest.',
        tags: ['Private Equity', 'Vertical SaaS', 'Healthcare'],
      },
      {
        slug: 'gridframe-convert',
        title: 'GridFrame Software Prices Convertible Notes',
        company: 'GridFrame Software',
        counterparty: 'Convertible Investors',
        dealType: 'Convertible Notes',
        category: 'DCM',
        dealSize: 560,
        sector: 'Enterprise Software',
        summary: 'GridFrame issued convertibles to fund product expansion while preserving near-term cash interest.',
        whyItMatters: 'Convertible structures remain a flexible bridge for growth software issuers.',
        tags: ['DCM', 'Convertibles', 'Enterprise Software'],
      },
      {
        slug: 'navcloud-titangpu',
        title: 'NavCloud and TitanGPU Form Inference Capacity Alliance',
        company: 'NavCloud',
        counterparty: 'TitanGPU',
        dealType: 'Capacity Partnership',
        category: 'Strategic Partnership',
        dealSize: null,
        sector: 'AI Infrastructure',
        summary: 'NavCloud secured committed capacity via a multi-year alliance with TitanGPU.',
        whyItMatters: 'Partnership-driven capacity procurement can reduce capex intensity for AI platform operators.',
        tags: ['Strategic Partnership', 'AI Infrastructure', 'Compute Capacity'],
      },
      {
        slug: 'bridgeline-amend-extend',
        title: 'BridgeLine Lending Completes Amend-and-Extend',
        company: 'BridgeLine Lending',
        counterparty: 'Direct Lender Group',
        dealType: 'Amend-and-Extend',
        category: 'Restructuring',
        dealSize: 440,
        sector: 'Fintech',
        summary: 'BridgeLine secured maturity extensions and covenant relief tied to cash preservation targets.',
        whyItMatters: 'Direct lenders continue to prefer extensions for borrowers with plausible stabilization plans.',
        tags: ['Restructuring', 'Fintech', 'A&E'],
      },
      {
        slug: 'clearinglake-series-c',
        title: 'ClearingLake Workflow Automation Raises Series C',
        company: 'ClearingLake Workflow Automation',
        counterparty: 'Harborview Growth',
        dealType: 'Series C',
        category: 'Venture Funding',
        dealSize: 205,
        sector: 'Capital Markets Tech',
        summary: 'ClearingLake raised growth capital to expand post-trade workflow automation for broker-dealers.',
        whyItMatters: 'Post-trade automation remains a high-conviction spend area for institutional market participants.',
        tags: ['Venture Funding', 'Capital Markets Tech', 'Post-Trade'],
      },
    ],
  }),
  createWeek({
    week: '2026-W01',
    title: 'Year Opens with Cross-Border Payments Consolidation and Robust Infrastructure Funding',
    startDate: '2025-12-29',
    endDate: '2026-01-04',
    marketSignal: {
      tone: 'Balanced',
      headline: 'Early-year deal flow showed strong strategic intent in payments and AI infrastructure.',
      detail:
        'Large strategic transactions led headlines while venture and debt markets supported scaled operators with clear growth trajectories.',
    },
    analystTake:
      'The opening tape suggests continued appetite for core rails and workflow ownership. Funding conditions remain selective but constructive for issuers with durable demand profiles.',
    featuredSlug: 'europay-harborswitch',
    deals: [
      {
        slug: 'europay-harborswitch',
        title: 'EuroPay Systems to Acquire HarborSwitch Gateway',
        company: 'HarborSwitch Gateway',
        counterparty: 'EuroPay Systems',
        dealType: 'Cross-Border Acquisition',
        category: 'M&A',
        dealSize: 3000,
        currency: 'EUR',
        sector: 'Payments',
        summary: 'EuroPay signed a cross-border acquisition to expand merchant acquiring and payout capabilities.',
        whyItMatters: 'Cross-border payments scale is increasingly strategic as regional compliance costs rise.',
        tags: ['M&A', 'Payments', 'Cross-border'],
      },
      {
        slug: 'promptledger-series-b',
        title: 'PromptLedger Compliance Copilot Raises Series B',
        company: 'PromptLedger Compliance Copilot',
        counterparty: 'North Ridge Ventures',
        dealType: 'Series B',
        category: 'Venture Funding',
        dealSize: 150,
        sector: 'Fintech',
        summary: 'PromptLedger raised growth capital to scale AI compliance copilots for banks and payment processors.',
        whyItMatters: 'Compliance automation remains a durable fintech growth theme with clear enterprise ROI.',
        tags: ['Venture Funding', 'Fintech', 'Compliance AI'],
      },
      {
        slug: 'plantops-buyout',
        title: 'Summit Ridge Acquires PlantOps Industrial SaaS',
        company: 'PlantOps Industrial SaaS',
        counterparty: 'Summit Ridge Capital',
        dealType: 'Sponsor Buyout',
        category: 'Private Equity / Buyouts',
        dealSize: 840,
        sector: 'Vertical SaaS',
        summary: 'Summit Ridge acquired PlantOps to build an industrial workflow software platform.',
        whyItMatters: 'Industrial vertical SaaS remains sponsor-attractive due to high retention and workflow lock-in.',
        tags: ['Private Equity', 'Vertical SaaS', 'Industrial Software'],
      },
      {
        slug: 'alphavenue-ipo',
        title: 'AlphaVenue Trading Tech Prices IPO',
        company: 'AlphaVenue Trading Tech',
        counterparty: 'Lead Bookrunner Group',
        dealType: 'IPO',
        category: 'ECM',
        dealSize: 710,
        sector: 'Capital Markets Tech',
        summary: 'AlphaVenue priced its IPO at the midpoint after demand from specialist technology funds.',
        whyItMatters: 'A functioning IPO path supports valuation confidence for late-stage capital markets software.',
        tags: ['ECM', 'IPO', 'Capital Markets Tech'],
      },
      {
        slug: 'neonstack-secured-notes',
        title: 'NeonStack Data Centers Issues Secured Notes',
        company: 'NeonStack Data Centers',
        counterparty: 'Institutional Credit Investors',
        dealType: 'Senior Secured Notes',
        category: 'DCM',
        dealSize: 2200,
        sector: 'AI Infrastructure',
        summary: 'NeonStack issued long-dated secured notes to fund incremental AI-ready campus capacity.',
        whyItMatters: 'AI data center debt is attracting institutional capital where demand visibility remains strong.',
        tags: ['DCM', 'AI Infrastructure', 'Data Centers'],
      },
      {
        slug: 'credaxis-metrobank',
        title: 'CredAxis and MetroBank Launch Embedded Issuing Program',
        company: 'CredAxis',
        counterparty: 'MetroBank',
        dealType: 'Embedded Finance Partnership',
        category: 'Strategic Partnership',
        dealSize: null,
        sector: 'Payments',
        summary: 'CredAxis partnered with MetroBank to offer embedded card issuing for vertical SaaS platforms.',
        whyItMatters: 'Bank-fintech partnerships remain the fastest path to scale embedded payment distribution.',
        tags: ['Strategic Partnership', 'Embedded Finance', 'Payments'],
      },
      {
        slug: 'clearwave-recap',
        title: 'ClearWave Lending Agrees Pre-Negotiated Recapitalization',
        company: 'ClearWave Lending',
        counterparty: 'Secured Creditor Committee',
        dealType: 'Pre-Negotiated Recapitalization',
        category: 'Restructuring',
        dealSize: 600,
        sector: 'Fintech',
        summary: 'ClearWave reached a creditor agreement to extend maturities and tighten risk controls.',
        whyItMatters: 'Early restructurings are helping lenders avoid value-destructive downside scenarios.',
        tags: ['Restructuring', 'Fintech', 'Recapitalization'],
      },
      {
        slug: 'taskriver-auditloop',
        title: 'TaskRiver Acquires AuditLoop Controls Platform',
        company: 'AuditLoop Controls Platform',
        counterparty: 'TaskRiver',
        dealType: 'Strategic Acquisition',
        category: 'M&A',
        dealSize: 980,
        sector: 'Enterprise Software',
        summary: 'TaskRiver acquired AuditLoop to expand governance and compliance workflows for enterprise clients.',
        whyItMatters: 'Enterprise software buyers continue to use targeted M&A to deepen platform breadth and retention.',
        tags: ['M&A', 'Enterprise Software', 'Governance Tech'],
      },
    ],
  }),
];

export const demoWeeklyDealIntelligence: WeeklyDealBrief[] = demoWeeklyDealBriefs;
export const demoDealCategories = DEAL_CATEGORIES;
